### ISSUE TITLE
Mapping parameters

### ISSUE THREAD

**Issue by Racoccoon** [RasmussenLab/vamb#100]
Hi,

I have a few questions concerning the mapping : 

1. Is it possible to use results from a previous mapping, where the mapping is done with every sample mapping to each fasta file of contigs (instead of mapping every samples reads on a concatenated fasta file of all samples) ?
2. The parameters used with minimap2 vary in your example (TL;DR: Here's how to run Vamb, part 3 and Recommended workflow part 4) as well as the rule in the snakemake workflow : 
- in the TL;DR : `minimap2 -t 8 -N 50 -ax sr catalogue.mmi /path/to/reads/sample1.fw.fq.gz /path/to/reads/sample1.rv.fq.gz | samtools view -F 3584 -b --threads 8 > /path/to/bam/sample1.bam`
- in the recommended section : `minimap2 -T almeida.fna -t 28 -N 5 -ax sr almeida.mmi sample1.forward.fastq.gz sample1.reverse.fastq.gz | samtools view -F 3584 -b --threads 8 > sample1.bam`
-in the snakemake: `minimap2 -t {threads} -ax sr {input.mmi} {input.fq} | grep -v "^@" | cat {input.dict} - | samtools view -F 3584 -b - > {output.bam} 2>{log}`
The parameter -N vary from 5 to 50 and is absent in the snakemake workflow, what would you recommend concerning this parameter ? (I also could not find the use of -T parameter in minimap2 manual)

Thank you in advance for your answer,
Jolann

**Comment by simonrasmu** [comment]
Hi Jolann,

1. If you want to run VAMB in the multi-split mode (ie the one presented in the paper and by far best performance) you have to follow the workflow and cannot use reads to individual assembly BAM files. 
2. The -N option is for how many secondary alignments that minimap2 should output, I think default is 5. I am actually not sure what is the best option here (I haven't benchmarked it) and it could be dependent on the dataset. Also, not sure of the -T option as well, @jakobnissen 

Best,
Simon

**Comment by jakobnissen** [comment]
I can't remember what the `-T` argument does, and I can't seem to find it in the documentation of `minimap` either. I wonder how it got there. W.r.t `N`, I seem to remember that a value of 5 was sufficient when benchmarking, but my memory is hazy here.

I'll remove the `-T` flag, and set `-N 5` both places. Closing as solved, but you're welcome to re-open it or open another issue.
