### ISSUE TITLE
TypeError: concatenate_fasta() got an unexpected keyword argument 'rename'

### ISSUE THREAD

**Issue by Jiulong-Zhao** [RasmussenLab/vamb#101]
Hi developer:
Thanks for your efforts to develop this software!
I referred to the pipeline you provided: 
"
Use Vamb's concatenate.py to make the FASTA catalogue of all your assemblies:
concatenate.py /path/to/catalogue.fna.gz /path/to/assemblies/sample1/contigs.fasta
/path/to/assemblies/sample2/contigs.fasta  [ ... ]
" 
and run it myself:
`python ~/soft/vamb-3.0.3/src/concatenate.py ./catalogue.fna.gz /home/mcs/gene/zjl/sanggouwan_sediment_virus/temp_meta/metaspades/3_0_3/contigs.fasta /home/mcs/gene/zjl/sanggouwan_sediment_virus/temp_meta/metaspades/3_12_15/contigs.fasta /home/mcs/gene/zjl/sanggouwan_sediment_virus/temp_meta/metaspades/3_21_24/contigs.fasta /home/mcs/gene/zjl/sanggouwan_sediment_virus/temp_meta/metaspades/9_0_3/contigs.fasta /home/mcs/gene/zjl/sanggouwan_sediment_virus/temp_meta/metaspades/9_12_15/contigs.fasta /home/mcs/gene/zjl/sanggouwan_sediment_virus/temp_meta/metaspades/9_21_24/contigs.fasta /home/mcs/gene/zjl/sanggouwan_sediment_virus/temp_meta/metaspades/12_0_3/contigs.fasta /home/mcs/gene/zjl/sanggouwan_sediment_virus/temp_meta/metaspades/12_12_15/contigs.fasta /home/mcs/gene/zjl/sanggouwan_sediment_virus/temp_meta/metaspades/12_21_24/contigs.fasta`

However, something is wrong as follows:
Traceback (most recent call last):
  File "/home/mcs/soft/vamb-3.0.3/src/concatenate.py", line 43, in <module>
    rename=(not args.keepnames))
TypeError: concatenate_fasta() got an unexpected keyword argument 'rename'

So, what's wrong with my command?
Thanks for your help!
Looking forward to your reply!
Jiulong

**Comment by simonrasmu** [comment]
Hi Jiulong,

I am not sure why you get this, it works on my end. Which python are you using and how did you install vamb (pip, conda, or git)?

Best,

Simon

**Comment by Jiulong-Zhao** [comment]
I installed vamb by conda.
My python is 3.6.10.
Actually, I first create the conda environment for your software phamb. And then I installed vamb in this conda environment. So I don't know if there are conflicts in this environment.
The conda lists are as follows:
`(phamb) [mcs@mcs1 viral_binning]$ conda list
# packages in environment at /home/mcs/miniconda3/envs/phamb:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
_openmp_mutex             4.5                       1_gnu    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
_pytorch_select           0.1                       cpu_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
asn1crypto                1.4.0                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
bcrypt                    3.2.0            py36h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
brotlipy                  0.7.0           py36h27cfd23_1003    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
bzip2                     1.0.8                h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
c-ares                    1.18.1               h7f8727e_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ca-certificates           2021.10.26           h06a4308_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cairo                     1.14.12              h8948797_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
certifi                   2021.5.30        py36h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cffi                      1.14.0           py36h2e261b9_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
charset-normalizer        2.0.4              pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
checkm-genome             1.1.3                      py_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
cryptography              35.0.0           py36hd23ed53_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cudatoolkit               10.2.89              hfd86e86_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
curl                      7.69.1               hbc83047_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cycler                    0.11.0             pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cython                    0.29.24          py36h295c915_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
dendropy                  4.5.2              pyh3252c3a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
docutils                  0.17.1           py36h06a4308_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
dropbox                   11.14.0          py36h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
expat                     2.4.4                h295c915_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
filechunkio               1.6                      py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
fontconfig                2.13.1               h6c09931_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
freetype                  2.11.0               h70c0345_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
fribidi                   1.0.10               h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ftputil                   3.2                      py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
glib                      2.63.1               h5a9c865_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
graphite2                 1.3.14               h23475e2_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
graphviz                  2.40.1               h21bd128_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
harfbuzz                  1.8.8                hffaf4a1_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
hmmer                     3.3.2                h1b792b2_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
htslib                    1.9                  ha228f0b_7    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
icu                       58.2                 he6710b0_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
idna                      3.3                pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
intel-openmp              2022.0.1          h06a4308_3633    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
jbig                      2.1                  hdba287a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
joblib                    1.0.1              pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
jpeg                      9d                   h7f8727e_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
k8                        0.2.5                h9a82719_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
kiwisolver                1.3.1            py36h2531618_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
krb5                      1.17.1               h173b8e3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
lcms2                     2.12                 h3be6417_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ld_impl_linux-64          2.35.1               h7274673_9    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libcurl                   7.69.1               h20c2e04_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libdeflate                1.0                  h14c3975_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
libedit                   3.1.20181209         hc058e9b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libev                     4.33                 h7f8727e_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libffi                    3.2.1             hf484d3e_1007    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgcc                    7.2.0                h69d50b8_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgcc-ng                 9.3.0               h5101ec6_17    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgfortran-ng            7.5.0               ha8ba4b0_17    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgfortran4              7.5.0               ha8ba4b0_17    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgomp                   9.3.0               h5101ec6_17    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libiconv                  1.15                 h63c8f33_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libpng                    1.6.37               hbc83047_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libsodium                 1.0.18               h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libssh2                   1.9.0                h1ba5d50_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libstdcxx-ng              9.3.0               hd4cf53a_17    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libtiff                   4.2.0                h85742a9_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libtool                   2.4.6             h295c915_1008    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libuuid                   1.0.3                h7f8727e_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libwebp-base              1.2.2                h7f8727e_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libxcb                    1.14                 h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libxml2                   2.9.12               h03d6c58_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
lz4-c                     1.9.3                h295c915_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
matplotlib-base           3.3.4            py36h62a2d02_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
metabat2                  2.15                 h137b6e9_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
minimap2                  2.21                 h5bf99c6_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
mkl                       2020.2                      256    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl-service               2.3.0            py36he8ac12f_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_fft                   1.3.0            py36h54f3939_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_random                1.1.1            py36h0573a6f_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ncurses                   6.1                  he6710b0_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ninja                     1.10.2               h5e70eb0_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy                     1.19.2           py36h54aff64_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy-base                1.19.2           py36hfa32c7d_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
olefile                   0.46                     py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
openjpeg                  2.4.0                h3ad879b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
openssl                   1.1.1m               h7f8727e_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
packaging                 21.3               pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pandas                    1.1.5            py36ha9443f7_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pango                     1.42.4               h049681c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
paramiko                  2.1.2                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pcre                      8.45                 h295c915_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
perl                      5.26.2               h14c3975_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pillow                    8.3.1            py36h2c7a002_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pip                       21.2.2           py36h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pixman                    0.40.0               h7f8727e_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ply                       3.11                     py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pplacer                   1.1.alpha19          h9ee0642_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
prodigal                  2.6.3                h779adbc_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
psutil                    5.8.0            py36h27cfd23_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pyasn1                    0.4.8              pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pycparser                 2.21               pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pygraphviz                1.3.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
pynacl                    1.4.0            py36h7b6447c_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pyopenssl                 17.0.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pyparsing                 3.0.4              pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pysam                     0.15.3           py36hda2845c_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
pysftp                    0.2.9                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
pysocks                   1.7.1            py36h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python                    3.6.10               h0371630_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python-dateutil           2.8.2              pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pytorch                   1.3.1           cpu_py36h62f834f_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pytorch-cpu               1.3.1                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pytz                      2021.3             pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pyyaml                    5.4.1            py36h27cfd23_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
readline                  7.0                  h7b6447c_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
requests                  2.27.1             pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
samtools                  1.9                 h8571acd_11    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
scikit-learn              0.21.3           py36hd81dba3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
scipy                     1.5.2            py36h0b6359f_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
setuptools                58.0.4           py36h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
six                       1.16.0             pyhd3eb1b0_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
snakemake                 3.13.3                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
sqlite                    3.31.1               h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
stone                     3.2.1              pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tk                        8.6.11               h1ccaba5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
torchvision               0.1.8                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
tornado                   6.1              py36h27cfd23_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
urllib3                   1.26.8             pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
vamb                      2.1.0            py36h516909a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
wget                      1.20.1               h20c2e04_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
wheel                     0.37.1             pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
wrapt                     1.12.1           py36h7b6447c_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
xz                        5.2.5                h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
yaml                      0.2.5                h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
zlib                      1.2.11               h7f8727e_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
zstd                      1.4.9                haebb681_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
`

Thanks a lot!

**Comment by jakobnissen** [comment]
Dear @Jiulong-Zhao 

I'm not entirely sure what is going on here. It looks like you're running an older version of Vamb itself. In older versions of Vamb, the keyword `rename` was not part of the `concatenate_fasta` function. This was added Feb 14, 2020. However, it was added at the same time as the script you are using was added. So I don't understand how you can have the script, yet not the keyword.

The version of Vamb you are using is from 2019, an older version. So somehow, you are running a script from a newer version of Vamb, but using an older version of Vamb.

**Comment by jakobnissen** [comment]
What is going on is probably that you have downloaded Vamb either through Phamb or by itself, then enter the `src` directory and use the script from there. However, you have _installed_ Vamb 2.1.0. So when you run the script in Vamb 3.0.3, it imports Vamb 2.1.0.

To solve it, install Vamb 3.0.3 or any version newer than 2.1.0.

Closing as solved, but you're welcome to re-open if you think it was not addressed.
