### ISSUE TITLE
Workflow envs vamb.yaml incorrect version label (v3.0.3)

### ISSUE THREAD

**Issue by AdamSorrel** [RasmussenLab/vamb#102]
There seems to be an issue in the `vamb.yaml` file in the `workflow/ens` folder. The resulting warning is:
```
WARNING: Did not find branch or tag '3.0.3', assuming revision or ref.
```
It seems that the tag should be `v3.0.3` in the last line ( currently `- git+https://github.com/RasmussenLab/vamb@3.0.3`).

**Comment by simonrasmu** [comment]
Hi Adam, 

Thanks! It has been corrected!

Best,

Simon
