### ISSUE TITLE
Missing file for concatenate

### ISSUE THREAD

**Issue by susheelbhanu** [RasmussenLab/vamb#108]
Hi,

I'm running `concatenate.py` on a couple of assemblies and am getting the below error:
```
Traceback (most recent call last):
  File "/work/projects/ensemble/tools/miniconda3/envs/vamb/bin/concatenate.py", line 41, in <module>
    filehandle = open(args.outpath, "w") if args.nozip else gzip.open(args.outpath, "wt", compresslevel=3)
  File "/work/projects/ensemble/tools/miniconda3/envs/vamb/lib/python3.7/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/work/projects/ensemble/tools/miniconda3/envs/vamb/lib/python3.7/gzip.py", line 168, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/work/projects/nomis/assemblies/virome_results/vamb/concatenated_viral_seqs.fna.gz'
```

I'm running `v3.0.2` of VAMB and my command looks like this:
```
conda activate vamb
concatenate.py /work/projects/nomis/assemblies/virome_results/vamb/concatenated_viral_seqs.fna.gz *_viral.fna
```

Is the output file not created by the script?

Thanks,
Susheel

**Comment by jakobnissen** [comment]
It is possible that you specified a path where the file could not be created. For example, if the directory `/work/projects/nomis/assemblies/virome_results/vamb/` does not exist, then Python can't create a file in that directory. Python's error message is a little confusing here.

Did the directory in which you attempted to create the file exist?

**Comment by susheelbhanu** [comment]
Okay, that makes sense. I'm using vamb in a snakemake workflow, so I suppose I'll have to create the directory first. Thanks for the quick response!

**Comment by Gennuo** [comment]
Hi,
I have similar problem with @susheelbhanu. 
I'm running concatenate.py on a couple of assemblies and getting the below error:
**FileNotFoundError:** **/work/wangg/test_data/my_vamb/t2/output/catalogue.fna.gz**

I'm running v3.0.8 of vamb and my command looks like this:
"for i in *; do echo concatenate.py cd /path/to/output/catalogue.fna.gz /path/to/assembly_output/$i/final_assembly.fasta ; done"
I created a folder for my output data, I have checked my path, and it exists.

**Comment by jakobnissen** [comment]
@Gennuo The path `/path/to/output/catalogue.fna.gz` is merely an example path. If the directory `/path/to/output` does not exist on your computer, Vamb will not be able to create a file there.
I will improve the error message.
