### ISSUE TITLE
Question about the setting of contigs.txt

### ISSUE THREAD

**Issue by B-1991-ing** [RasmussenLab/vamb#109]
Dear vamb support team,

I am reading the tutorial of the VAMB snakemake workflow.

For the contigs.txt, is it okay to have the same name for all contigs files as "contigs.fasta" from different folders like below? Do I need to name the contig files uniquely? Or the file name isn't important, because they finally will be concatenated together in one file? 

./metaSPAdes_assemble/Sample1/contigs.fasta
./metaSPAdes_assemble/Sample2/contigs.fasta
./metaSPAdes_assemble/Sample3/contigs.fasta
./metaSPAdes_assemble/Sample4/contigs.fasta
./metaSPAdes_assemble/Sample5/contigs.fasta
./metaSPAdes_assemble/Sample6/contigs.fasta

Best,

Bing

**Comment by jakobnissen** [comment]
Yes, it should be fine. Closing as solved.

**Comment by B-1991-ing** [comment]
Okay. Thank you very much for your reply.
