### ISSUE TITLE
CreateCondaEnvironmentException

### ISSUE THREAD

**Issue by B-1991-ing** [RasmussenLab/vamb#110]
Dear vamb support team,

Our Computerome support team helped us install the vamb snakemake workflow on the HPC cluster. I directly entered the command line under my HPC directory. But, I got error shown below. Could you help me check the reason?

**The vamb snakemake workflow**
https://github.com/RasmussenLab/vamb/tree/master/workflow

**The vamb snakemake workflow command line** 
<img width="1348" alt="Screenshot 2022-04-21 at 00 07 16" src="https://user-images.githubusercontent.com/54441633/164333034-31039be0-06e0-45ac-9f26-02f2379e3629.png">

**Error**
Error in activate the conda environment (before running the vamb snakemake workflow command line)
<img width="1355" alt="Screenshot 2022-04-21 at 00 11 10" src="https://user-images.githubusercontent.com/54441633/164333577-c66b3431-8bdc-44e9-8c58-f96a6004c388.png">

Error in the vamb snakemake workflow (after I entered the vamb snakemake workflow command line)
<img width="1347" alt="Screenshot 2022-04-21 at 00 01 35" src="https://user-images.githubusercontent.com/54441633/164332956-827b9abd-62e4-41b4-a3a3-d9ed6d21af6a.png">

 Best,

Bing

**Comment by B-1991-ing** [comment]
Dear vamb support team,

Updated

I entered "conda init bash" on my HPC terminal. Then closed and restarted HPC terminal.

The I entered command lines below and errors appeared then.

conda activate vamb

module load /services/tools/anaconda3/4.4.0

module load anaconda3/4.4.0

snakemake --jobs 20 --configfile /home/projects/env_10000/people/binson/Current_pipeline/binning/vamb/config.json --snakefile /services/tools/vamb/3.0.3b/vamb/workflow/vamb.snake.conda.py --latency-wait 60 --use-conda --cluster "qsub -l walltime=12:00:00 -l nodes=1:ppn=32 -l mem=200gb" 

**Error screenshot**
<img width="1363" alt="Screenshot 2022-04-21 at 00 37 00" src="https://user-images.githubusercontent.com/54441633/164336235-0989774d-0bd5-4cc8-934f-4b0d1699ea9c.png">

Best,

Bing

**Comment by B-1991-ing** [comment]
Dear vamb support team,

**Updated**

**Solution**
**module load snakemake/6.9.1**
**module load conda_for_gatk/4.1.8.1**

**Snakemake command line running**
conda activate vamb
configuration_file=/home/projects/env_10000/people/binson/Current_pipeline/binning/vamb/config.json
snakemake --jobs 4 --configfile ${configuration_file} --snakefile /services/tools/vamb/3.0.3b/vamb/workflow/vamb.snake.conda.py --latency-wait 60 --use-conda --cluster "qsub -l walltime=12:00:00 -l nodes=2:ppn=16 -l mem=200gb" 

**New error**
CreateCondaEnvironmentException:
Could not create conda environment from /services/tools/vamb/3.0.3b/vamb/workflow/envs/checkm.yaml
<img width="1340" alt="Screenshot 2022-04-21 at 21 10 38" src="https://user-images.githubusercontent.com/54441633/164535775-a34746fd-8ed7-42a6-9aa3-435ba0699672.png">

**Question**
Must the HPC have the dependencies for each *.yaml (*.yaml are under /services/tools/vamb/3.0.3b/vamb/workflow/envs/)?
For example, the HPC must have "PyTorch, pip, torch vision, cudatoolkit=10.2, pysam" for building the vamb.yaml?
<img width="820" alt="Screenshot 2022-04-22 at 10 03 34" src="https://user-images.githubusercontent.com/54441633/164645068-d3a65ce6-f704-4b1c-8d35-5498a37cc616.png">


Best,

Bing

**Comment by jakobnissen** [comment]
This looks to be an issue with your HPC environment and Conda - not with Vamb. As such, I don't think we can really help from here. The reason is probably that you don't have permissions to create new Conda environments. You should contact your local HPC support team to solve this.

Another option is to contact your local HPC team and have them help you install Vamb directly, so that you can load Vamb as a module.

Closing this, as the error is not directly related to Vamb.

**Comment by B-1991-ing** [comment]
Dear vamb support team,

Our HPC support team already installed the vamb as a module tool under the path of "/services/tools/vamb/3.0.3b" as shown below. 
<img width="877" alt="Screenshot 2022-04-22 at 11 38 29" src="https://user-images.githubusercontent.com/54441633/164680401-b246d605-afa5-401a-a1ed-b4cc1ee9ab71.png">

And, also created the conda environment as shown below.
<img width="1042" alt="Screenshot 2022-04-22 at 11 36 30" src="https://user-images.githubusercontent.com/54441633/164680441-1a74797b-7583-4391-9e5b-d09b6a92eefa.png">

I will then ask them the location of the conda environment.

Best,

Bing

**Comment by B-1991-ing** [comment]
Dear vamb support team,

Our HPC support team said they already installed the vamb **as shown below**. But, I really can't find the conda vamb environment using "conda activate vamb" or "source activate vamb". So, I have one question and one suggestion. My question is that do we also need to install the VAMB snakemake workflow even after updating to 3.0.3 version? My suggestion is that could you combine the VAMB snakemake workflow into the whole vamb package, so it would be clearer for people to install on their platform. 

<img width="877" alt="Installation" src="https://user-images.githubusercontent.com/54441633/164916550-0c484c02-1b3e-46e2-be42-8504e4567f1d.png">

<img width="1062" alt="Screenshot 2022-04-22 at 10 46 21" src="https://user-images.githubusercontent.com/54441633/164916511-c7e5e181-1d37-4138-a1b8-dfec9d428850.png">

<img width="744" alt="Screenshot 2022-04-23 at 11 00 18" src="https://user-images.githubusercontent.com/54441633/164916591-d1f27e05-61aa-4681-9ef1-c5fb9533e561.png">

Best,

Bing

**Comment by B-1991-ing** [comment]
Dear vamb support team,

**Update**

Our HPC support team told me the way to run vamb command line on our HPC platform as shown below, which is a little different with the tutorial. Hope it can also give other people some hints when dealing with their errors.

The vamb command line:
module load tools
module load miniconda3/4.12.0
module load vamb/3.0.3b
module load samtools/1.14
module load minimap2/2.6
module load snakemake/6.0.4
configuration_file=/home/projects/env_10000/people/binson/Current_pipeline/binning/vamb/config.json
snakemake --jobs 4 --configfile ${configuration_file} --snakefile /services/tools/vamb/3.0.3b/vamb/workflow/vamb.snake.conda.py --latency-wait 10

Best,

Bing
