### ISSUE TITLE
Error in rule vamb: KeyError: 'S4CNODE_2946_length_5195_cov_4.089293\n'

### ISSUE THREAD

**Issue by B-1991-ing** [RasmussenLab/vamb#112]
Dear vamb support team,

I directly ran the vamb command line below using my metaSPAdes assemble output, but KeyError: 'S4CNODE_2946_length_5195_cov_4.089293\n' occurred during the step of "rule vamb" as shown below. Could you help us check how to solve the error?

**The vamb command line:**
module load tools
module load miniconda3/4.12.0
module load vamb/3.0.3b
module load samtools/1.14
module load minimap2/2.6
module load snakemake/6.0.4
configuration_file=/home/projects/env_10000/people/binson/Current_pipeline/binning/vamb/config.json
snakemake --jobs 4 --configfile ${configuration_file} --snakefile /services/tools/vamb/3.0.3b/vamb/workflow/vamb.snake.conda.py --latency-wait 10 

**Error:**
<img width="1351" alt="Screenshot 2022-04-26 at 08 41 48" src="https://user-images.githubusercontent.com/54441633/165237844-d9b2020a-24b6-448c-b7c7-9726d85a9d5c.png">

**Error log in rule vamb**
[vamb.log](https://github.com/RasmussenLab/vamb/files/8560619/vamb.log)

**Whole complete running log**
[log6.log](https://github.com/RasmussenLab/vamb/files/8560623/log6.log)

Thank you very much.

Best,

Bing

**Comment by jakobnissen** [comment]
Could you post Vamb's own log file, created in the Vamb output directory?

**Comment by B-1991-ing** [comment]
Thank you very much for your reply. Here is Vamb's own log file.

**Screenshot**
<img width="1310" alt="Screenshot 2022-04-26 at 09 13 00" src="https://user-images.githubusercontent.com/54441633/165243134-d57fe763-c95d-4353-a091-f871373b0fb5.png">

**File**
[vamb.log](https://github.com/RasmussenLab/vamb/files/8560719/vamb.log)

**Comment by jakobnissen** [comment]
This is not Vamb's own logfile, but `snakemake`'s. Vamb's logfile can be found in the Vamb output directory and is called `log.txt`

**Comment by B-1991-ing** [comment]
Here it is, from directory "/home/projects/env_10000/people/binson/Current_pipeline/binning/vamb/output".

[log.txt](https://github.com/RasmussenLab/vamb/files/8560750/log.txt)

**Comment by B-1991-ing** [comment]
My metaSPAdes contigs.fasta looks like shown below.

<img width="1267" alt="Screenshot 2022-04-26 at 09 22 34" src="https://user-images.githubusercontent.com/54441633/165244559-85931efa-d08b-4266-819e-c46c82ef0fb4.png">

**Comment by jakobnissen** [comment]
Thank you. This looks like a serious bug in Vamb, I will investigate immediately.

**Comment by B-1991-ing** [comment]
You're welcome, waiting for your reply.

**Comment by jakobnissen** [comment]
The bug has now been fixed on master. I will create a new release v3.0.6 which includes this bugfix.
You can find the change here:
https://github.com/RasmussenLab/vamb/commit/aeab6ece87f2b846e9d8af6306cd196ca591eec9#diff-91f4a9f9495717456e138b1b18d06f95c16e0d93245617ac053d8d47e9059f07L371-R371
If you don't want to re-install Vamb, you can work around it in two ways:
* If you have a "source install" of Vamb, you can simply edit the source code, and it will take effect. If you installed Vamb using `pip install -e .`, that will be the case.
* Alternatively, you can manually create your bins. The bins should be present in `clusters.tsv` in the Vamb output directory. They should already have been binsplit. You just need to read the FASTA file and split it according to the clusters described in `clusters.tsv`.

Closing as solved, but you're welcome to write if you have more information.

**Comment by B-1991-ing** [comment]
Thank you very much for your help and quick response. 

I will email our HPC support team to ask help on the source code editing, as I don't have permission. 

Have a nice day.
