### ISSUE TITLE
"MissingOutputException" occurred due to the parameter - "--latency-wait 60"

### ISSUE THREAD

**Issue by B-1991-ing** [RasmussenLab/vamb#113]
Dear vamb support team,

I go "**MissingOutputException**" due to the paprameter. - "--latency-wait 60" as shown in the snakemake log file - "". Would it affect my vamb binning results finally? If yes, I want to rerun the vamb command line with different value for the parameter **"--latency-wait 120" or with  "--latency-wait 180"**? Could you give me some suggestion on the setting of this parameter?

**Command lines in my qsub script - vamb_binning.sh.txt:**
module load tools
module load miniconda3/4.12.0
module load vamb/3.0.6
module load samtools/1.14
module load minimap2/2.6
module load snakemake/6.0.4
configuration_file=/home/projects/env_10000/people/binson/Current_pipeline/binning/vamb/config.json
snakemake --jobs 5 --configfile ${configuration_file} --snakefile /services/tools/vamb/3.0.3b/vamb/workflow/vamb.snake.conda.py **--latency-wait 60** 

**The vamb_binning.sh.txt:**
[vamb_binning.sh.txt](https://github.com/RasmussenLab/vamb/files/8571708/vamb_binning.sh.txt)

**The way I submit the vamb_binning.sh on HPC:**
qsub -W group_list=env_10000 -A env_10000 -l nodes=10:ppn=16,walltime=24:00:00 /home/projects/env_10000/people/binson/scripts/vamb_binning.sh

**vamb log** (from the dir: /home/projects/env_10000/people/binson/Current_pipeline/binning/vamb/output)
[vamb_log.txt](https://github.com/RasmussenLab/vamb/files/8571654/vamb_log.txt)

**snakemake log**(from the dir: /home/projects/env_10000/people/binson)
[vamb_binning.err.txt](https://github.com/RasmussenLab/vamb/files/8571676/vamb_binning.err.txt)

**empty vamb.log**(from the dir: /home/projects/env_10000/people/binson/log/vamb)
<img width="836" alt="Screenshot 2022-04-27 at 13 47 10" src="https://user-images.githubusercontent.com/54441633/165511560-7bcb6cb0-dd78-4112-9e45-58d5714742ec.png">

Thank you very much.

Best,

Bing

**Comment by B-1991-ing** [comment]
Hi Simon,

Thank you very much for your reply. Then, I will go further step.

I checked my vamb bins output folder - **/home/projects/env_10000/people/binson/Current_pipeline/binning/**vamb/output/bins**/**, where already **144 SXCXXX.fna** files exists. The "clusters.tsv", "latent.npz", "lengths.npz", "log.txt", "mask.npz", "model.pt", "tnf.npz" are under the folder - **/home/projects/env_10000/people/binson/Current_pipeline/binning/**vamb/output/**.

Before seeing your GitHub reply, I already reran it as shown below at yesterday afternoon. **Still 91% finished with showing the same error, due to the changing of the output folder.**

Command lines in my qsub script - vamb_binning.sh.txt:
module load tools
module load miniconda3/4.12.0
module load vamb/3.0.6
module load samtools/1.14
module load minimap2/2.6
module load snakemake/6.0.4
configuration_file=/home/projects/env_10000/people/binson/Current_pipeline/binning/vamb/config.json
snakemake --jobs 5 --configfile ${configuration_file} --snakefile /services/tools/vamb/3.0.3b/vamb/workflow/vamb.snake.conda.py **--latency-wait 240** 

The way I submit the vamb_binning.sh on HPC:
qsub -W group_list=env_10000 -A env_10000 -l nodes=10:**ppn=24,mem=800gb,walltime=32:00:00** /home/projects/env_10000/people/binson/scripts/vamb_binning.sh

Best,

Bing

**Comment by jakobnissen** [comment]
Something weird is happening: The workflow assumes the Vamb output directory is called `vamb`, but your output directory seems to be `vamb/output` instead. This would cause `snakemake` to fail.
@B-1991-ing Is it possible you have some kind of post-processing command that moves the vamb output directory from `vamb` to `vamb/output`?

**Comment by B-1991-ing** [comment]
Hi Jakob,

Thank you very much for reminding **the default setting of "--outdir vamb"**.

I specifically named **the output directory as "vamb/output"**, as I want the vamb put all results directly into the folder - "vamb/output". So, I didn't directly set the parameter - "--outdir" as "--outdir vamb".

I will try to run it again, just to be safe.

Best,

Bing

**Comment by jakobnissen** [comment]
Ah, then there is the problem. The workflow does not work if you override `--outdir`.
Closing as solved.

**Comment by B-1991-ing** [comment]
Dear vamb support team,

Finally, 100% finished, with the setting of "--outdir vamb".

<img width="1361" alt="Screenshot 2022-04-28 at 18 45 39" src="https://user-images.githubusercontent.com/54441633/165803168-1e81d3cf-d198-4a61-a618-5c0a718799ba.png">

Thank you very much for every help and comment.

Best,

Bing
