### ISSUE TITLE
why there is no cluster more than single squence 

### ISSUE THREAD

**Issue by huangl07** [RasmussenLab/vamb#121]
Hi

I have already check the vamb to binning my file with jgi files 

`vamb --fasta total.seq --jgi contig.depth  --outdir vamb1 -o C -m 2000 --minfasts 200000`

but I check all the bins files, they are all only have one sequence

I wonder know why ?

thankyou

**Comment by huangl07** [comment]
I have already find out that the sequence ID must be start as ”S*C“ and fix it

although I don't know why

record it

**Comment by jakobnissen** [comment]
It's difficult for us to know why all your clusters only have one sequence.
It's not necessarily that your sequence names must be of the form `S*C`. Vamb should work with a broad range of sequence formats.
It's more likely that you are clustering a small number of sequences (e.g. < 50.000), or that your depth mapping is not accurate.

I recommend reading the README.md and tutorial at `doc/tutorial.ipynb` to find information on what is going wrong.
Until we get any more information, we can't act on this issue, so closing. You're welcome to re-open if you get more information about what is happening.
