### ISSUE TITLE
Do the vamb parameters in config.json file overwrite those in vamb.snake.conda.py script?

### ISSUE THREAD

**Issue by liangjinsong** [RasmussenLab/vamb#126]
Hi, when run vamb by the following snakemake command:
snakemake --cores 192 --configfile /NFSfile/wangjuntao/combined_contigs/config.json --snakefile /home/jinsong/software/vamb-3.0.8/workflow/vamb.snake.conda.py

Both of the two files in the command above contain vamb parameters, e.g. the config.json file contains something like that "_vamb_params": "-l 24 -n 384 384 -p 190 -o C -m 2000 --minfasta 2000 --outdir vamb_L24_N384_", and the vamb.snake.conda.py file contains something like that "_VAMB_PARAMS = config.get("vamb_params", "-l 32 -n 512 512 -p 190 -o C -m 2000 --minfasta 2000")_".

I wonder do the vamb parameters in the config.json file overwrite those in the vamb.snake.conda.py script when running the snakemake command above?

Thank you in advance.

**Comment by jakobnissen** [comment]
Yes, they do. The syntax in the snakefil `config.get(key, default)`, means "get `key` from the config file, and if not found, use the default instead."
