### ISSUE TITLE
In file jgi.abundance.dat, the third column is exactly equal to the fouth coulun

### ISSUE THREAD

**Issue by liangjinsong** [RasmussenLab/vamb#128]
I found that in file jgi.abundance.dat, the third column is exactly equal to the fouth coulun. Is this a mistake? Does it mislead the binning results? I use version 3.0.8, I also see the same issue in prior versions.

**Comment by jakobnissen** [comment]
If I recall correctly, third column is the sum (Orr is it mean?) of columns 4, 6, 8 etc. If you have only one sample, column three and four are equal. So it's OK.

**Comment by liangjinsong** [comment]
I found this issue when dealing with more than one samples. 
See an example from the table of https://github.com/RasmussenLab/vamb/issues/83

**Comment by liangjinsong** [comment]
I found this issue when dealing with more than one samples.
See an example from the table of #83 (https://github.com/RasmussenLab/vamb/issues/83)



梁金松
LIANG Jinsong


手机(Mobile):+86-18565801115
广东省深圳市南山区桃源街道深圳大学城哈尔滨工业大学校区，518055
School of Civil & Environmental Engineering, Harbin Institute of Technology, Shenzhen 518055, China
---- Replied Message ----
| From | Jakob Nybo ***@***.***> |
| Date | 7/22/2022 17:29 |
| To | ***@***.***> |
| Cc | Liang ***@***.***> ,
***@***.***> |
| Subject | Re: [RasmussenLab/vamb] In file jgi.abundance.dat, the third column is exactly equal to the fouth coulun (Issue #128) |

If I recall correctly, third column is the sum (Orr is it mean?) of columns 4, 6, 8 etc. If you have only one sample, column three and four are equal. So it's OK.

**Comment by jakobnissen** [comment]
Okay I was too quick there. I'm on holiday, but will take a look next week

**Comment by jakobnissen** [comment]
Now I understand your issue.
The Vamb workflow creates a dummy JGI file by copy-pasting from multiple single-sample JGI files. This means the third column will be wrong.
This does not impact Vamb, as it only extracts the numbers from columns 4 an onwards.
Upcoming releases of Vamb will migrate away from using the `jgi_summarize_bam_contig_depths` as part of the Snakemake workflow and will itself call `CoverM`. This will be faster, easier and more accurate.
