### ISSUE TITLE
Error in VAMB

### ISSUE THREAD

**Issue by dannyionescu** [RasmussenLab/vamb#131]
Hi, 
I am trying to use vamb as below and am getting this error:

UnboundLocalError: local variable 'dumpdirectory' referenced before assignment

This is the whole trace as it appears:
Traceback (most recent call last):
  File "/home/dionescu/miniconda3/envs/vamb/bin/vamb", line 11, in <module>
    sys.exit(main())
  File "/home/dionescu/miniconda3/envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 476, in main
    logfile=logfile)
  File "/home/dionescu/miniconda3/envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 219, in run
    len(tnfs), minalignscore, minid, subprocesses, logfile)
  File "/home/dionescu/miniconda3/envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 125, in calc_rpkm
    shutil.rmtree(dumpdirectory)
UnboundLocalError: local variable 'dumpdirectory' referenced before assignment

This is my command (after running jgi_summarize_bam_contig_depths)
vamb --outdir ./vamb_bins --fasta ./contigs_catalogue.fna --jgi ./sorted_catalogue_depth

In the output folder I get the following files generated:
172K Aug 11 23:58 lengths.npz
 398 Aug 11 23:58 log.txt
22M Aug 11 23:58 rpkm.npz
39M Aug 11 23:58 tnf.npz

The contig catalogue file contains ca. 250K contigs (concatenated manually). When installing vamb with conda the concatenations scripts are not downloaded. Mapping was done with minimap2

Hope there is an easy solution,

Thanks,

Danny

**Comment by jakobnissen** [comment]
That looks like a bug in Vamb. Can you check which version of Vamb you are using?

**Comment by dannyionescu** [comment]
I installed vamb using conda. vamb -h shows no version and there seems there is no -v or --version option. On the anaconda website the vamb version is 3.02 updated almost 6 months ago (https://anaconda.org/bioconda/vamb). Therefore, I think I am using this version

**Comment by dannyionescu** [comment]
I now reinstalled vamb using pip getting v.3.08 and it is running without errors.

**Comment by jakobnissen** [comment]
Okay nice. I'm closing this, but will fix the issue if I figure out what happened.
