### ISSUE TITLE
Two important parameters in index command need be edited accordingly

### ISSUE THREAD

**Issue by liangjinsong** [RasmussenLab/vamb#133]
I guess that two important parameters in the index command (_minimap2 -I {INDEX_SIZE} -d {output} {input} 2> {log}_) need be edited accordingly by users.

Firstly, minimap2 uses different presets to index reference file (suffix _.fa_ or _.fna_) to make sure the index file (suffix _.mmi_) matchs query reads produced on specific sequcing platform. According to _https://github.com/lh3/minimap2/blob/master/minimap2.1_, an index parameter of "-x sr" create a type of index file that matchs short reads (~100-150 bp) produced on Illumina; while the default index mode is "-x map-ont", which would creates an index file that match noisy long reads of ~10% error rate. See a screenshot below, which is from https://github.com/lh3/minimap2/blob/master/minimap2.1.
![图片](https://user-images.githubusercontent.com/43932337/187026411-a4203e48-b0fa-4285-a86a-dce20a344752.png)

The index command in the file _vamb.snake.conda.py (v3.0.8)_  is _minimap2 -I {INDEX_SIZE} -d {output} {input} 2> {log}_, which would use the default "-x map-ont" mode to create an index file that match noisy long reads of ~10% error rate. However, mapping short and accurate reads produced on Illunina platform are the most cases.  Hence, I suggest add "-x sr" to the index command to make a index file that matchs short reads (~100-150 bp) produced on Illumina.

Secondly, the default "INDEX_SIZE" in the file _vamb.snake.conda.py (v3.0.8)_is "12G". If the base number in the input file (e.g. contigs.flt.fna.gz) is greater than 12G, an "multi-part index" issue will occur, and will cause incorrect mapping quality. See last paragraph of a screenshot below, which is from https://github.com/lh3/minimap2/blob/master/minimap2.1. Hence, I suggest to set a larger value than the base number in your input file (e.g. contigs.flt.fna.gz) for "-I" to guarantee the mapping quality.

![图片](https://user-images.githubusercontent.com/43932337/187026357-7a9e5b6b-d4de-4e01-af64-14c7a6c1a1d1.png)

**Comment by jakobnissen** [comment]
Thanks for your thorough issue.

However, I think these suggestions are not necessary for Vamb.
`minimap2` has a rather bizarre bug where, if the index is given too little RAM, the output SAM file will contain multiple SAM headers interspersed in the SAM file. In other words, the SAM file will be invalid, and Vamb will crash.

To prevent this in the workflow, we have to resort to an ugly hack:
* First we index the FASTA file with minimap2 and `INDEX_SIZE` RAM, knowing that this RAM amount may be insufficient
* Then, we create a SAM header using `samtools dict`, and save it in a separate file
* Then, we perform our mapping with the Illumina-optimal option `-ax sr` as you recommend, and filter away any SAM headers from the output
* Finally, we concatenate the SAM header from the `samtools dict` step with the above minimap2 mapping to obtain a full SAM file which is not broken.

Regarding the "mapping quality", I believe `minimap2` refers to the MAPQ field of the SAM records, which gives the probability that a read is mismapped. I don't think "mapping quality" here refers to the actual quality of mapping. The MAPQ field cannot be accurately calculated if the aligner cannot store in memory all the alternative mapping positions. However, Vamb does not use the MAPQ field anyway, as the MAPQ computation is unreliable with a metagenomic dataset. So, I believe the actual mapping quality does not deteriorate when `minimap2` does not have the entire index in RAM, only the unused MAPQ field. 

Closing this as solved, but if you have any comments please do re-open and let us know.
