### ISSUE TITLE
DistributionNotFound

### ISSUE THREAD

**Issue by Gennuo** [RasmussenLab/vamb#134]
Dears,

I found an issue here. Could you give me any suggestions? Thank you.

pkg_resources.DistributionNotFound: The 'vamb==3.0.8' distribution was not found and is required by the application

**Comment by jakobnissen** [comment]
When does the error occur?

**Comment by Gennuo** [comment]
Hi, thank you for your asking. 
when I run the step"Use Vamb's concatenate.py to make the FASTA catalogue of all your assemblies".

It was works before when I use only one final_assembly.fasta file to run, and I can run all the steps. But it does not work when I run more than one final_assembly.fasta file. And I use the script to run all my data: 
**for i in *; do concatenate.py /path/to/catalogue.fna.gz /path/to/assemblies/$i/final_assembly.fasta ; done**.

**Comment by jakobnissen** [comment]
It looks like you might not have properly installed Vamb. Can you open a Python REPL and see if you can `import vamb`?
