### ISSUE TITLE
samtools view: error closing "-"

### ISSUE THREAD

**Issue by Gennuo** [RasmussenLab/vamb#135]
Dear vamb teams,

When I use one sample to run the below step, I got an error (I already got catalogue.mmi) :
**minimap2 -t 8 -N 5 -ax sr catalogue.mmi /../../../QC_output/Co1-13_/Co1-13_1.fastq.tar.gz /../../../QC_output/Co1-13_/Co1-13_2.fastq.tar.gz | samtools view -F 3584 -b --threads 8 > /../../../outputs/bam/Co1-13_.bam**

And Co1-13_1.fastq.tar.gz is my forward file, Co1-13_1.fastq.tar.gz is the reverse file. They both be put in the folder **QC_output/Co1-13_**

[WARNING] Indexing parameters (-k, -w or -H) overridden by parameters used in the prebuilt index.
[WARNING] For a multi-part index, no @SQ lines will be outputted. Please use --split-prefix.
[M::main::8.494*1.00] loaded/built the index for 1144190 target sequence(s)
[M::mm_mapopt_update::8.494*1.00] mid_occ = 1000
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1144190
[M::mm_idx_stat::9.354*1.00] distinct minimizers: 69396725 (24.14% are singletons); average occurrences: 10.676; average spacing: 5.399; total length: 4000265187
[E::sam_parse1] no SQ lines present in the header
samtools view: error reading file "-": Inappropriate ioctl for device
[E::sam_parse1] no SQ lines present in the header
samtools view: error closing "-": -5

Could you have any suggestions to help me to improve? Thank you.

**Comment by jakobnissen** [comment]
Dear @Gennuo 

This is an issue with `minimap2`. When you build the index, it needs to be all in memory. (see option `-I` when building index). If it's not, then `minimap2` will create multiple indices which each fit into memory.
When mapping against multiple indices, `minimap2` does not by default create temporary files. The workaround is to either set `-I [MEM]` with enough memory to make sure the entire index can be in RAM, or else to set `--split-prefix [PREFIX]` when mapping.

We will fix the command on Vamb's README.md.

**Comment by Gennuo** [comment]
Hello @jakobnissen,

Thank you for your reply. **I did not understand where I should add the -I?**
I run the command: minimap2 -t 8 -N 5 -ax sr catalogue.mmi /../../../QC_output/Co1-13_/Co1-13_1.fastq.tar.gz /../../../QC_output/Co1-13_/Co1-13_2.fastq.tar.gz | samtools view -F 3584 -b --threads 8 > /../../../outputs/bam/Co1-13_.bam. 

I try to add the -I, but I got the same error. Thank you.
