### ISSUE TITLE
question about coassembly approaches

### ISSUE THREAD

**Issue by Valentin-Bio** [RasmussenLab/vamb#141]
Hello developer!, reading your documentation I noticed that vamb yields better binning results by binning separated assemblies. On the suggested workflow , it is recommended to run vamb using `-o` flag , the purpose of this flag is to determine the contigs belonging to each sample of the concatenated fasta?  if so, what is the recommended workflow for binning form coassembled contigs?

I have 30 environmental metagenomic samples which came from 30 independent samples, I coassembled them and I ran vamb under the following code:

`vamb --outdir ${dir}/vamb_output --fasta coassembly/final.contigs.fa --jgi ${dir}/metabat2/depth.txt --minfasta 200000`

I didn't use the `-o` flag , but not sure what were the consequences of removing that flag. I assumed that if my contigs are a product of coassembly , I don't have need to use that flag am I right?

Best regards,

Valentín.

**Comment by jakobnissen** [comment]
Yes, that's right. With a coassembly, you can use the same options, but omit the `-o` option which will not be useful for co-assemblies.

Closing this issue as solved - you're welcome to reopen if you have more questions
