### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'output_dir/tmp/pycoverm'

### ISSUE THREAD

**Issue by yazhinia** [RasmussenLab/vamb#167]
Hello,
         I get the following error while calling `vamb` in the command line from parsebam.py script 
`FileNotFoundError: [Errno 2] No such file or directory: 'output_dir/tmp/pycoverm'` 

pycoverm is installed in my environment. When I call abundance.from_files() from Jupyter notebook, it works. 
Wondering what is missing for a command line run?

Thanks for your help.

Best,
Yazhini

**Comment by jakobnissen** [comment]
Dear @yazhinia 

Thanks for the bug report. This is probably a bug in Vamb, but it's difficult to tell.
Could you post the version of Vamb you are running and the full stack trace? I'll try to hunt down the bug.

**Comment by jakobnissen** [comment]
Closed in #168 - you can upgrade to Vamb 4.1.1 to get the fix (or fix it manually by implementing the fix in #168 yourself). Thanks again for the report.
