### ISSUE TITLE
workflow_avamb error: avamb_manual_drep_disjoint_clusters.tsv: No such file or directory

### ISSUE THREAD

**Issue by lzk98** [RasmussenLab/vamb#185]
Hi,
When i run workflow_avamb, the error find in rule 'write_clusters_from_nc_folders' as follow:

`/public/home/software/vamb/workflow_avamb/src/write_clusters_from_dereplicated_and_ripped_bins.sh: line 29: avamb_outdir/avamb/avamb_manual_drep_disjoint_clusters.tsv: No such file or directory
Waiting at most 60 seconds for missing files.
MissingOutputException in rule write_clusters_from_nc_folders in file /public/home/software/vamb/workflow_avamb/avamb.snake.conda.smk, line 678:
Job 0 completed successfully, but some output files are missing. Missing files after 60 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
avamb_outdir/avamb/avamb_manual_drep_disjoint_clusters.tsv
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message`

I'm not sure how to solve this problem. Can you please help me?

**Comment by jakobnissen** [comment]
This might happen if the binning yields zero NC bins, in which case the right thing would be to create an empty file, however the shell script `write_clusters_from_dereplicated_and_ripped_bins.sh` used in the current workflow does not create a file at all.
It might also be another problem.

@Paupiera can you verify and possibly fix? Otherwise I can do it when back from holiday.

**Comment by lzk98** [comment]
Hi, I fixed the above error
Replaced `rule write_clusters_from_nc_folders` in avamb.snake.conda.smk:
`    shell:
        "sh {params.path} -d {OUTDIR}/Final_bins -o {OUTDIR} ;"
        "touch {log.log_fin} "`
and write_clusters_from_dereplicated_and_ripped_bins.sh as folllow:
`#!/usr/bin/bash
while getopts "d:o:" opt; do
  case $opt in
    d) drep_dir=$OPTARG    ;;
    o) clusters_file=$OPTARG    ;;
    *) echo 'error' >&2
       exit 1
  esac
done
output_file=$(pwd)/${clusters_file}/avamb/avamb_manual_drep_disjoint_clusters.tsv
echo 'creating z y v clusters from the final set of bins'
for s in $(ls $drep_dir)
do
s="$drep_dir"/"$s"/
if [ -d "$s" ]
then
cd $s
for bin in $(ls . 2> /dev/null)

do  
if [[ $bin == **".fna" ]]
then

cluster_name=$(echo $bin | sed 's=.fna==g' | sed 's=.fa==g')

for contig in $(grep '>' $bin | sed 's=>==g') 
do
echo -e   "$cluster_name""\t""$contig"  >> $output_file
done


fi
done

fi
done `

**Comment by Paupiera** [comment]
Dear Izk98,

Thanks for using AVAMB. I now implemented your suggested changes as part of the workflow.

Thanks for you contribution,
Best
Pau
