### ISSUE TITLE
Error: Discrepancy between BAM and FASTA headers when running VAMB

### ISSUE THREAD

**Issue by dayanne09** [RasmussenLab/vamb#186]
Hi,
I'm encountering an error with VAMB while running the program. The error message indicates a discrepancy between the headers of the BAM file (output_L.bam) and the corresponding headers in the reference FASTA file. I have already checked that both the BAM and FASTA files have the same headers in the same order, but the error persists.

**ValueError: BAM file output_L.bam has reference hash 7c12af3bd14bcb75bebcf0dfa298c528, expected 0d5a6c824338c37c3ddd5a84e3e90f8c. Verify that all BAM headers and FASTA headers are identical and in the same order.** 

I would greatly appreciate any assistance in resolving this issue. If anyone has encountered a similar error or knows a potential solution, please let me know. Your help will be invaluable in troubleshooting this problem and allowing me to proceed with my work.

Thank you in advance for your support!

**Comment by jakobnissen** [comment]
I'll look into it. Can you please provide the following to help me narrow down what might cause the issue:

* The version of Vamb you used (it's in the `log.txt` output file)
* The full stack trace (i.e. the full Python error)
* The content of the `log.txt` file

**Comment by dayanne09** [comment]
Hi, 
I have attached the files with the information you asked for.
[log.txt](https://github.com/RasmussenLab/vamb/files/12099710/log.txt)
[vamb_L_job.o125199.txt](https://github.com/RasmussenLab/vamb/files/12099721/vamb_L_job.o125199.txt)

Thanks for your help.

**Comment by jakobnissen** [comment]
I think I've found the source of the issue - see https://github.com/RasmussenLab/vamb/issues/225#issuecomment-1763362080
In short: Either update to the latest version of Vamb, or re-check the BAM and FASTA file to see if the headers really are identical.
Closing as solved. Please re-open if I'm wrong.
