### ISSUE TITLE
Error due to "--model vae" in snakemake pipeline (AVAMB 4.1.3)

### ISSUE THREAD

**Issue by bhimbbiswa** [RasmussenLab/vamb#196]
Hi,

I don't know if I made some mistake or if we cannot select only "vae"  in AVAMB snakemake pipeline.

My main goal is to get viral bins using phamb from output of VAMB.

So I used AVAMB 4.1.3 snakemake pipeline with the following config

```
{
   "contigs": "/MAGs/Vamb/230728/contigs.txt",
   "sample_data": "/MAGs/Vamb/230728/samples2data.txt",
   "index_size": "35G",
   "min_contig_size": "2000",
   "min_bin_size": "200000",
   "min_identity": "0.95",
   "minimap_mem": "700GB",
   "minimap_ppn": "20",
   "avamb_mem": "700GB",
   "avamb_ppn": "20",
   "checkm2_mem": "700GB",
   "checkm2_ppn": "20",
   "checkm2_mem_r": "700GB",
   "checkm2_ppn_r": "20",
   "avamb_params": " --model vae -o C  --seed 0 ",
   "avamb_preload": "",
   "outdir": "avamb_outdir",
   "min_comp": "0.9",
   "max_cont": "0.05"
}
```

Even though I am using only VAMB, still snakemake searched for "aae_z_clusters.tsv, aae_y_clusters.tsv" and after not finding them, deleted "avamb_outdir" directory.

So my question is "From now we cannot use only VAMB in Snakemake or I made some mistake."

Please find attached my log file.

Regards,

Bhim

[AVAMB_log.txt](https://github.com/RasmussenLab/vamb/files/12434790/AVAMB_log.txt)

**Comment by jakobnissen** [comment]
Dear @bhimbbiswa 

It's not possible to select only the VAE in the AVAMB pipeline.
We might want to re-think the whole pipeline thing for Vamb.

Closing as solved.
