### ISSUE TITLE
 'hmmsearch ' operation take a lot of time ...

### ISSUE THREAD

**Issue by ChaoXianSen** [RasmussenLab/vamb#222]
Hi !
I refer to  "https://github.com/RasmussenLab/phamb/tree/master#how-to-run---not-in-parallel---quick-and-dirty"

'hmmsearch --cpu 16 \
                    -E 1.0e-05 \
                    -o output.txt \
                    --tblout annotations/all.hmmVOG2.tbl \
                    /01_Database/AllVOG.hmm  \
                    test_vamb/proteins.faa

why this step runs slowly, taking a lot of timefile ? 
File 'all.hmmVOG.tbl ' generation spent ~25 hours . ( file 'proteins.faa' is about 300M in size )

thanks !

**Comment by jakobnissen** [comment]
I think this question is outside the scope of VAMB itself - this concerns another program, namely `HMMER`.
