### ISSUE TITLE
Example work folwo QC step

### ISSUE THREAD

**Issue by Lamm-a** [RasmussenLab/vamb#23]
In your example workflow QC step you only use AdapterRemoval which does not trim low quality regions in reads, rather only at the 3' prim end after adapter removal. Was this a conscious choice and if so why?

**Comment by jakobnissen** [comment]
No, there is no reason to use any particular read trimmer, as long as it does its job. In essence, you just want long, correctly assembled contigs, and BAM files containing all correct (i.e. above your requested homology level) alignments from reads to your contigs. If you have trimmers assemblers or aligners which you think do a better job than AdapterRemoval, metaSPAdes and minimap2, just use those.

P.s.: I'm not updated on the best trimmers, but yes, you're right that just looking at 3' ends is not enough. Is there a tool you prefer to AdapterRemoval?

**Comment by Lamm-a** [comment]
Okay thank you :) I am am also not upto date with the best tools but I hear good things about [Trimomatic](http://www.usadellab.org/cms/?page=trimmomatic) and [BBDUK](http://seqanswers.com/forums/showthread.php?t=42776).

**Comment by jakobnissen** [comment]
Thanks, I'll take a look at it.
