### ISSUE TITLE
Output source clusters for bins when binsplitting

### ISSUE THREAD

**Issue by jakobnissen** [RasmussenLab/vamb#237]
Currently, when binsplitting with `-o`, the original identity of the cluster from which a bin derives from is lost. This could be useful for some users. We could consider:
1. Naming the bins after the clusters, e.g. instead of `vae_1`, call it `vae_c1_b1` for cluster 1, or
2. Write a separate file in which the cluster identity of each bin is written, or
3. Write a more in-depth log file with metadata about the generated Cluster objects

**Comment by simonrasmu** [comment]
I vote for solution 2
