### ISSUE TITLE
How do we provide  vamb.vambtools.concatenate_fasta with the sample numbers for appropriate contig header labeling?

### ISSUE THREAD

**Issue by Lamm-a** [RasmussenLab/vamb#25]
The help for the tool says:
```
concatenate_fasta(outpath, inpaths, minlength=2000)
    Creates a new FASTA file from input paths, and rename contig headers
    to the pattern "S{sample number}C{contig identifier}".
```

It appears there is no input for sample number, how does the tool then work out sample number, is it from the file name and then if so should we have a recomended file labeling structure?

Thanks :)

**Comment by jakobnissen** [comment]
Dear @Lamm-a 

Yep, the function will simply enumerate the input files from 1 to N. If you use `concatenate_fasta`, you simply need to make sure that no contigs in the same file has the same name - the function will also raise an error if that happens.
