### ISSUE TITLE
After using the default vamb call should we then follow every step in your tutorial document to obtain the best binXX.fa files?

### ISSUE THREAD

**Issue by Lamm-a** [RasmussenLab/vamb#26]
I have just run the vamb on default perameters and am not looking to actually generated binXX.fa files but am a biut stuck as to where i should start. You provide alot of useful info n your tutorial document but I feel I am getting lost in it. Would you be able to point me in the righ direction?

Thank you for all the help :)

**Comment by jakobnissen** [comment]
This is a more complicated issue, and I'm not sure I'm able to point you in the right direction. What do you want to achieve? Are you looking for bacteria? All bacteria? Specific bacteria? Compare strains? Discover new genes? Metagenomic binning can be used for lots of things.

This is somewhat out of the scope of Vamb - do you have any specific questions regarding Vamb?

**Comment by Lamm-a** [comment]
I am looking to make bins for all bacteria present in the metagenome to understand the community composition at first. Since you ask, one of the analyses I wish to do is to compare strain diversity (within each bin) and how it spreads through samples in my dataset (I used a co-assembly as the basis for the bins).
In short, my scaffolds are relatively fragmented and would like to use binning to get as complete genomes as possible.

**Comment by jakobnissen** [comment]
I would run Vamb, and filter the resulting clusters for a reasonable minimum size to filter way too small/large bins out. Then, I'd run a quality control tool like CheckM with some relaxed criteria to filter the obviously highly contaminated out. Last, I'd align each gene in the contigs to a database and do some manual annotation of your bins.
