### ISSUE TITLE
Can vamb.cluster.ClusterGenerator() take length as input as described in tutorial document?

### ISSUE THREAD

**Issue by yazhinia** [RasmussenLab/vamb#264]
Hi,
    I find that the vamb.cluster.ClusterGenerator() takes only latent matrix as an input and not the contig length which to my understanding is used to sort contigs before clustering and compute length-weighted mean distance. Does the clustering algorithm not use length information anymore?

Thank you.

Best,
Yazhini

**Comment by jakobnissen** [comment]
Dear @yazhinia 

It's the other way around. It used to only take the matrix, but now takes the matrix and a vector of lengths. Maybe you got an old version of Vamb? You can check it like this:
```
>>> import vamb
>>> vamb.__version__
(4, 1, 3
```
The latest version is 4.1.3

**Comment by yazhinia** [comment]
Thank you. I was using vamb 4.1.1. The new version (4.1.3) works better.
