### ISSUE TITLE
vamb ValueError: TNF row at index 160128 is all zeros.

### ISSUE THREAD

**Issue by ChaoXianSen** [RasmussenLab/vamb#276]
Dear @sgalkina 
pipeline : $vamb --outdir ${outdir} \
                --fasta  ${fname}.contigs_headNoSpace.fa \
                --bamfiles ${fname}_sort_changed_header.bam

The error is as follows:  

Traceback (most recent call last):
  File "/public/home/bioinfo_wang/00_software/miniconda3/envs/avamb/bin/vamb", line 33, in <module>
    sys.exit(load_entry_point('vamb', 'console_scripts', 'vamb')())
  File "/public/home/bioinfo_wang/00_software/vamb/vamb/__main__.py", line 1387, in main
    run(
  File "/public/home/bioinfo_wang/00_software/vamb/vamb/__main__.py", line 768, in run
    data_loader = vamb.encode.make_dataloader(
  File "/public/home/bioinfo_wang/00_software/vamb/vamb/encode.py", line 113, in make_dataloader
    raise ValueError(
ValueError: TNF row at index 160128 is all zeros. This implies that the sequence contained no 4-mers of A, C, G, T or U, making this sequence uninformative.This is probably a mistake. Verify that the sequence contains usable information (e.g. is not all N's)

All of the other samples that I've run are going to work, but the only two samples that I've run are going to go wrong, What went wrong ?

Looking forward to your reply !

**Comment by jakobnissen** [comment]
Have you checked the DNA/RNA sequence number 160128 in your FASTA file, as indicated by the error message? Does its content look normal?

**Comment by ChaoXianSen** [comment]
the bam file number 160128 :
![6ab74268df09184ef98dd87eb5a6db1](https://github.com/RasmussenLab/vamb/assets/26301954/2803f578-3277-49ba-a7ff-902b232dc778)

 its content look normal.

**Comment by jakobnissen** [comment]
Which version of Vamb are you running?

**Comment by ChaoXianSen** [comment]
![b6882532ea4ba38fd85d966c318a2df](https://github.com/RasmussenLab/vamb/assets/26301954/9b8abf69-105a-45c4-9687-55c054d59192)

**Comment by jakobnissen** [comment]
Also, the BAM record you posted contains the 160128th read, whereas the error pertains to the 160128th contig. Can you check that in the FASTA file?

**Comment by jakobnissen** [comment]
Ah, that file contains contigs shorter than 2 kbp, which are filtered away.
Is there an output file called "contignames"? In that, find the 160128th contig name, and use the name of that contig to find the sequence.
Sorry for the hassle!

**Comment by ChaoXianSen** [comment]
pipeline : 
vamb --outdir ${fname} \
--fasta ${fname}.contigs_headNoSpace.fa
--bamfiles ${fname}_sort_changed_header.bam

'${fname}.contigs_headNoSpace.fa' is the raw contig (assembly for megahit, contains sequecnes shorter than 2 kbp),

I jsut want to use vamb to get the file 'cluster.tsv' to further analysis ( vamb -> PHAMB);  

Sample F183 , program runs with an error , not produced the file  'contignames'. 
![5f0212b8b7d3448c54b27c2d40da7bf](https://github.com/RasmussenLab/vamb/assets/26301954/468e9df5-66c4-42ad-a5c7-5e43a3a2e74a)

But, another sample F1, the file 'contignames' like this :It doesn't seem to delete  contigs shorter than 2 kbp:
![5c82311006cf6957b1529aba75e6455](https://github.com/RasmussenLab/vamb/assets/26301954/3b70bab9-dd47-4c1e-90e8-1828d5144629)

**Comment by jakobnissen** [comment]
Okay. I still need to see that contig 160128 looks good.
Can you run the following code in the directory which failed, such that it has access to the file `composition.npz`?
```python
import vamb
comp = vamb.parsecontigs.Composition.load("composition.npz")
N = 160128
N = 21
print(comp.metadata.lengths[N])
print(comp.metadata.identifiers[N])
print(comp.matrix[N])
```

**Comment by ChaoXianSen** [comment]
![76f7381c35fa1fc12c8f58b6632613d](https://github.com/RasmussenLab/vamb/assets/26301954/96a486fe-280e-4234-bc30-8d97a66b9f58)
![e40cff446b0851633549458e2bab566](https://github.com/RasmussenLab/vamb/assets/26301954/a76d1ed8-bf93-4806-9121-a91e402af4cd)
![524d698f2e0becea986967842a208ff](https://github.com/RasmussenLab/vamb/assets/26301954/35da1eab-fa4f-4c8b-a58d-b8d8ad831d5e)

its content look normal.

**Comment by jakobnissen** [comment]
Okay, I found the bug! This is indeed a bug in Vamb and has nothing to do with your particular sequence.
It just so happens that the vector you print has a sum that is exactly zero, and this causes a bug in Vamb.
I'll push a fix ASAP.

**Comment by ChaoXianSen** [comment]
![1b4ce92d3f9f485eaceaeb8c24b4321](https://github.com/RasmussenLab/vamb/assets/26301954/c35d16ef-6ba2-4a39-a09e-d4aaacf3b840)

through the log file, It doesn't seem to Creating and training VAE~

**Comment by ChaoXianSen** [comment]
> Okay, I found the bug! This is indeed a bug in Vamb and has nothing to do with your particular sequence. It just so happens that the vector you print has a sum that is exactly zero, and this causes a bug in Vamb. I'll push a fix ASAP.


so that's how matters stand, thanks for your reply. Thank you very much for your help !

**Comment by ChaoXianSen** [comment]
I have another question , the running speed of avamb seems to slowly,  What can I do to speed process up  ?
pipeline :
vamb --outdir ${fname}
--fasta ${fname}.contigs_headNoSpace.fa
--bamfiles ${fname}_sort_changed_header.bam

**Comment by jakobnissen** [comment]
Your best bet would be to use a GPU, and set `--cuda` when running. This will speed up training and clustering quite a bit.
What step in particular is slow? You can check the log file.

**Comment by ChaoXianSen** [comment]
> Okay, I found the bug! This is indeed a bug in Vamb and has nothing to do with your particular sequence. It just so happens that the vector you print has a sum that is exactly zero, and this causes a bug in Vamb. I'll push a fix ASAP.


![2643b02539d01b55736542b0e0a5a5e](https://github.com/RasmussenLab/vamb/assets/26301954/39b14d44-1e3c-4934-85df-aa558770df87)
 the vector is this comp.matrix[N] ?  sum(comp.matrix[N]) does not seem to be equal to zero ?

**Comment by ChaoXianSen** [comment]
> Your best bet would be to use a GPU, and set `--cuda` when running. This will speed up training and clustering quite a bit. What step in particular is slow? You can check the log file.

![2f9a2219f07c959862944c5b5e9cc8b](https://github.com/RasmussenLab/vamb/assets/26301954/a24aba3e-8b77-4a71-a63b-8428d9db1438)

![f487b12fecda74c7caa52fc97a5a88d](https://github.com/RasmussenLab/vamb/assets/26301954/c69278ee-850d-4893-8e8f-b95b1383f007)
the process of  Creating and training VAE is slow, which can I improve ? look forward for your reply again !

**Comment by ChaoXianSen** [comment]
> > sum(comp.matrix[N]) does not seem to be equal to zero ?
> 
> Hmm... it's possible that this is because it's computed slightly differently in Vamb, so there might be some rounding error where it may return either 3.79e-9 or 0.0, depending on the exact order of the floating point operations.

OKOK  ,i get it. thanks a lot !
