### ISSUE TITLE
Merging VAE and AAE clusters w/o snakemake workflow?

### ISSUE THREAD

**Issue by jnesme** [RasmussenLab/vamb#280]
Hi Jakob et al.

I am running VAMB/AVAMB on a dataset in a stepwise manner (ie. not through the avamb snakemake workflow) and I was wondering if there is a small how-to somewhere to merge the binning results, using checkM2 results on all clusters ? I would like to avoid re-running all steps from the raw reads 

I can do it "manually" following the snakemake file operations but I was wondering if I am not missing an obvious ressource somewhere that would help me do that faster ?

Best,
Joseph.

**Comment by jakobnissen** [comment]
Dear Joseph,

We don't have any 'official' resource to do that - manually running the steps of the workflow is your best bet.
Closing as solved - but you're of course welcome to reopen if you have more questions.

Br
Jakob
