### ISSUE TITLE
When filtering bins using your provided script, what is the input?

### ISSUE THREAD

**Issue by Lamm-a** [RasmussenLab/vamb#29]
I am looking to filter the bins by size using your script provided:

```
def splitclusters(clusters, sep):
    # First split by sample
    split = dict()
    for n, (clustername, contigs) in enumerate(clusters.items()):
        for contig in contigs:
            samplename = contig.partition(sep)[0]
            newclustername = 'c' + str(n) + '_' + 's' + samplename
            if newclustername in split:
                split[newclustername].add(contig)
            else:
                split[newclustername] = {contig}
    return split

def filterclusters(clusters, lengthof):
    # Now filter away the small bins
    filtered_bins = dict()
    for medoid, contigs in clusters.items():
        binsize = sum(lengthof[contig] for contig in contigs)
    
        if binsize >= 200000:
            filtered_bins[medoid] = contigs
    
    return filtered_bins
        
lengthof = dict(zip(contignames, lengths))
filtered_bins = filterclusters(splitclusters(clusters, '_'), lengthof)
print('Number of bins before splitting and filtering:', len(clusters))
print('Number of bins after splitting and filtering:', len(filtered_bins))

```
Is clusters just the cluster.tsv output by vamb, then what is length of and sep? I assume sep is the seperator in the contig names in the format  {Samplename}{Separator}{X}?

**Comment by jakobnissen** [comment]
When running Vamb from command line, the clusters are most easily split with the `-o` option. In the tutorial where you are looking, the splitting step is done manually. In the newer versions of Vamb, there is a splitting function (`vamb.vambtools.binsplit`). 

In the tutorial example, `contigs` is calculated in the cell above. You can see that it is a `dict` with `str` keys and `set` values. However, the code in the tutorial is better though of as an example showing the internal workings of Vamb, not really a stable easy to use interface for using Vamb effectively.

**Comment by Lamm-a** [comment]
When using the `-o` option nothing seems to change on the output, and I still come across the same issues of how to actually get to the stage of having individual `fasta` files per bin.

**Comment by jakobnissen** [comment]
Running with `-o` does change the output. If you run with a version before 2.1.0 (to be more precise, before commit 6e16a3f), then the bin names will not tell you that they have been split, but they will still have been. In the latest version of Vamb, the bin names clearly tell they have been split. For example, cluster 1 will be called `C1` before split, and after split, bins from e.g. sample "S5" it will be called `S5_1`.

To get the FASTA files, there are multiple ways: 
1) You can do it manually. It's really just going through the `clusters.tsv` file and picking out the FASTA entries with names matching each bin. Not too hard.
2) You can use the provided script `src/create_fasta.py`. Not too hard, either.
3) You can switch to the `master` branch and use the newest functionality, where Vamb does it automatically.

Yout don't really need to go through the tutorial to do this. I'd say that's easy enough for all relevant users.

**Comment by jakobnissen** [comment]
Closing this issue as the original issue is solved. You're welcome to re-open or open another one.
