### ISSUE TITLE
Question about output bins file name

### ISSUE THREAD

**Issue by MapleHe** [RasmussenLab/vamb#298]
**Vamb version: 3.0.3**

May I ask whether I can assume that,  similar contigs/bins of each sample/individual will have identical contig/bin ID ?

For example in output bins folder I have:
S1C1.fna
S1C2.fna
S2C1.fna
S2C3.fna

May I say that S1C1 and S2C1 are actually from the same cluster, which means they might come from the same species ?
If so, I am thinking that I can use dereplication tools to further refine each cluster separately.

**Other information**
Input format:
- fasta: 
```text
>S1CNODE_1_length_xxx_cov_xxxx
ATCGATCGATCGATCG
```
- jgi: 
```text
contigName    contigLen    totalAvgDepth    sampleName1    sampleName2
S1CNODE_1_length_xxx_cov_xxxx    500000    6.6    0.01
```

I shall apologize if I just missed the information in your document.
Thanks for the brilliant tool.

**Comment by jakobnissen** [comment]
Yes, for Vamb 3.0.3, that's correct, you can assume that.
However, this is not something we have previously guaranteed. We'll only guarantee that from Version 5 (the upcoming version) onward. However, if you stick to v 3.0.3, then that's the case.

Closing as solved. You're welcome to re-open it or make another issue :)
