### ISSUE TITLE
netowrkx does not exist

### ISSUE THREAD

**Issue by B1991ing** [RasmussenLab/vamb#300]
Dear vamb support team,

I want to install AVAMB snakemake workflow according to the official instruction, but **netowrkx does not exist** as shown in the screenshot. How to solve it?

**official instruction**
<img width="997" alt="截屏2024-04-15 19 43 54" src="https://github.com/RasmussenLab/vamb/assets/155892166/ac874c29-9d66-43d6-a1aa-3a192fdf1822">

**netowrkx does not exist**
<img width="540" alt="截屏2024-04-15 19 40 58" src="https://github.com/RasmussenLab/vamb/assets/155892166/67ee68f5-784a-47ed-bf6f-8bbe57894f00">

Best,

Bing

**Comment by jakobnissen** [comment]
That screenshot appears to be from an old version of this github repo. If you visit the newest one, you'll find the updated instructions: https://github.com/RasmussenLab/vamb/tree/master/workflow_avamb

**Comment by B1991ing** [comment]
> That screenshot appears to be from an old version of this github repo. If you visit the newest one, you'll find the updated instructions: https://github.com/RasmussenLab/vamb/tree/master/workflow_avamb

Thank you for yor reply, but I always got errors when git clone -b release-4.1 https://github.com/RasmussenLab/vamb.git.

Error-screenshot1:
![image](https://github.com/RasmussenLab/vamb/assets/155892166/8cf0653e-58de-402f-b9a6-205930c70d20)

Error-screenshot2:
![image](https://github.com/RasmussenLab/vamb/assets/155892166/e81f0014-a943-4f3b-b0a1-cb5e9a87f6ce)

**Comment by jakobnissen** [comment]
Hm, not sure why your `git clone` doesn't work. But this doesn't look like an issue with Vamb.

**Comment by B1991ing** [comment]
> Hm, not sure why your `git clone` doesn't work. But this doesn't look like an issue with Vamb.

Hi Jakob,

New errors occurred as shown in the screenshot when installating --- ** cd CheckM2  && git checkout e563159 && python setup.py install && cd ..**.

**Installation:**
<img width="980" alt="截屏2024-04-17 15 24 32" src="https://github.com/RasmussenLab/vamb/assets/155892166/2ac14939-9219-41f8-be93-8784e0712709">

**Error screenshot - part1:**
<img width="1511" alt="截屏2024-04-17 15 22 39" src="https://github.com/RasmussenLab/vamb/assets/155892166/792fbf12-7b24-4b90-8c0c-d0ff5e4c5f20">

**Error screenshot - part2:**
<img width="1511" alt="截屏2024-04-17 15 24 01" src="https://github.com/RasmussenLab/vamb/assets/155892166/25b1165a-1b41-4142-8f0d-b0a1791395ca">

Best,

Bing

**Comment by B1991ing** [comment]
> > Hm, not sure why your `git clone` doesn't work. But this doesn't look like an issue with Vamb.
> 
> Hi Jakob,
> 
> New errors occurred as shown in the screenshot when installating --- ** cd CheckM2 && git checkout e563159 && python setup.py install && cd ..**.
> 
> **Installation:** <img alt="截屏2024-04-17 15 24 32" width="980" src="https://private-user-images.githubusercontent.com/155892166/323120725-2ac14939-9219-41f8-be93-8784e0712709.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNTczMDMsIm5iZiI6MTcxMzM1NzAwMywicGF0aCI6Ii8xNTU4OTIxNjYvMzIzMTIwNzI1LTJhYzE0OTM5LTkyMTktNDFmOC1iZTkzLTg3ODRlMDcxMjcwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxMjMwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTI1YjVhNmJmMWFlY2VkMTUzOWRjODAyY2JjY2M1ZjI3Y2NiMDRiNTc5ZTM4YzA3ZDI5YmU4ZWRiNTEwOTIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xWXFqxVsRbJ6wxsiHalxnaGIke0LfSdmsM3-6R_qtd8">
> 
> **Error screenshot - part1:** <img alt="截屏2024-04-17 15 22 39" width="1511" src="https://private-user-images.githubusercontent.com/155892166/323120162-792fbf12-7b24-4b90-8c0c-d0ff5e4c5f20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNTczMDMsIm5iZiI6MTcxMzM1NzAwMywicGF0aCI6Ii8xNTU4OTIxNjYvMzIzMTIwMTYyLTc5MmZiZjEyLTdiMjQtNGI5MC04YzBjLWQwZmY1ZTRjNWYyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxMjMwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOGZkMmEzNTE1YTUwNDU2NzA3MzIzYzc2YzhmY2M1ZDZiYTBmMWI4MDhlMWQxNGM1MjVmZmYyOWNiZjExZjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qapUJNEF0Xkum-e-ufmjLVpIWQ9Wd0ZyHytWiTedJcc">
> 
> **Error screenshot - part2:** <img alt="截屏2024-04-17 15 24 01" width="1511" src="https://private-user-images.githubusercontent.com/155892166/323120578-25b1165a-1b41-4142-8f0d-b0a1791395ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNTczMDMsIm5iZiI6MTcxMzM1NzAwMywicGF0aCI6Ii8xNTU4OTIxNjYvMzIzMTIwNTc4LTI1YjExNjVhLTFiNDEtNDE0Mi04ZjBkLWIwYTE3OTEzOTVjYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxMjMwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYWNhMTg3YWIwMWZkMGYwM2Q2YmNjNzEzNWMzYWExZWY2Y2VmODc4ZDRkOGU3NTQ1NmE0NjUyY2ExMjJiOTBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ElXEVG99UesclbZpb71xMD57Wc-Ct0wfgJ9a1dchJUQ">
> 
> Best,
> 
> Bing

I tried many times for the same command line, finally it was successfully installed. But, I am not very sure that it can run smoothly. I'll try it later.
