### ISSUE TITLE
which output file used to assess MAG quality with CheckM

### ISSUE THREAD

**Issue by ChaoXianSen** [RasmussenLab/vamb#308]
Hi @jakobnissen，

I am using Vamb 1.4.3 ：

vamb --outdir test_VAMB_bam  \
          --fasta test_contigs.fa  \
          --bamfiles test_sorted.bam 

outputs: 
![image](https://github.com/RasmussenLab/vamb/assets/26301954/82388eef-22f0-43c5-9ba8-f7462680975c)

Which file should be used as input when assessing MAG quality with CheckM?

Thank you very much in advance.

**Comment by jakobnissen** [comment]
vae_clusters.tsv contains the bins in text format. I believe CheckM needs the bins as individual FASTA files. You can create these using the Contigo catalogue and the vae_clusters.tsv, optionally using the script in the src/ folder of VAMB.

**Comment by jakobnissen** [comment]
Closing as solved - you're welcome to re-open or continue commenting here if you have more questions
