### ISSUE TITLE
No module named 'vamb'

### ISSUE THREAD

**Issue by B1991ing** [RasmussenLab/vamb#309]
Update

Hi Jakob,

I installed workflow_avamb, checkm2, and snakemake using mamba, but new error happened that ModuleNotFoundError in file **/work/home/songbing/vamb/workflow_avamb/avamb.snake.conda.smk, line 4: 
No module named 'vamb'
File "/work/home/songbing/vamb/workflow_avamb/avamb.snake.conda.smk", line 4, in <module>**
<img width="943" alt="截屏2024-04-24 11 56 52" src="https://github.com/RasmussenLab/vamb/assets/155892166/d0050c05-d15e-4b44-9d47-dfc1536d2037">

**script**
[diarrhea_cecum_vamb_binning.sh.txt](https://github.com/RasmussenLab/vamb/files/15087596/diarrhea_cecum_vamb_binning.sh.txt)

**Installation**
[vamb_installation.txt](https://github.com/RasmussenLab/vamb/files/15087604/vamb_installation.txt)

How to solve this?

Best,

Bing

**Comment by jakobnissen** [comment]
Follow the instruction on the screen - you need to initialize your Mamba install using `mamba init`.

**Comment by B1991ing** [comment]
> Follow the instruction on the screen - you need to initialize your Mamba install using `mamba init`.

I already tried **mam init**, but doesn't work.

mamba init
mamba activate snakemake
mamba activate avamb
mamba activate checkm2

#sbatch -J diarrhea_cecum_vamb_binning -p xahcnormal -N 1 --ntasks-per-node=1 --cpus-per-task=20 --mem=256 -t 720:00:00 /work/home/songbing/scripts/diarrhea_cecum_vamb_binning.sh
#,jobid  14917419, 23.4.2024
configuration_file=/work/home/songbing/scripts/config_diarrhea_cecum.json
/work/home/songbing/miniforge3/envs/snakemake/bin/snakemake --cores 20 --configfile ${configuration_file} --snakefile /work/home/songbing/vamb/workflow_avamb/avamb.snake.conda.smk --use-conda

mamba deactivate
mamba deactivate
mamba deactivate
