### ISSUE TITLE
Using cudu not possible from Conda installation

### ISSUE THREAD

**Issue by gisleDK** [RasmussenLab/vamb#31]
For running with GPU goodness the Conda package still needs some parts. The installation of pytorch-gpu (https://anaconda.org/anaconda/pytorch-gpu) contains the missing parts.

**Comment by jakobnissen** [comment]
Thanks for bringing this to my attention.

I'm wary of adding pytorch-gpu as a dependency, for two reasons. First, it's a quite heavyweight dependency (presumably 100s of MB) that only a minority of users will need. Second, it does not support MacOS, meaning that Vamb would not be installable from Conda on a Mac.

I've [added a comment](https://github.com/RasmussenLab/vamb/commit/1c6283179df563040b09d4178783889fd8e9a0ba) in the README.md.
