### ISSUE TITLE
Performance of binsplitting

### ISSUE THREAD

**Issue by apcamargo** [RasmussenLab/vamb#33]
HI @jakobnissen!

Both in the README and the tutorial you recommend users to use binsplitting because it provides better results. Do you have compared the performance of sample-wise binning vs. binsplitting? I couldn't find it in your paper and I'm very interested in this.

**Comment by jakobnissen** [comment]
Hey @apcamargo 

Yes, we have made several comparisons between samplewise splitting and binsplitting. Unfortunately, our paper have been in the submit-review-reject-resubmit cycle for about 18 months now (so the paper on bioRxiv is very outdated by now).

In our experiments we can reconstruct 28-105% more unique genomes at high recall and precision when using binsplit relative to sample-wise binning. Some of the genomes have only a few contigs, and so are easily reconstructed. When considering only genomes with >5 contigs, we find 109-282% more genomes.

In fact, on smaller datasets, the majority of performance improvements of Vamb over MetaBAT2 can be attributed to binsplitting. When binsplitting is added to MetaBAT2, Vamb performs only slightly better.

Again, these results have not yet been peer reviewed! When (if) the Vamb paper comes through the review process, I will update the readme.

**Comment by jakobnissen** [comment]
By the way, I *think* the reason for the superior performance of binsplitting is that it solves an annoying dilemma

* If using multiple samples, similar strains and species from your different samples will cluster together and contaminate each other
* If running in single-sample mode, you have much less statistical power from the contig abundances, and so much less signal.

It also depends on your definition of a "high-precision genome". If you don't mind that your bins have contamination from closely related genomes, say with 90% or 95% nucleotide identity, then the effect of binsplitting is less impressive.

**Comment by apcamargo** [comment]
That's very interesting. I'd guess that concatenating the assemblies would mess up the abundance estimation due to species sharing between related samples.

**Comment by jakobnissen** [comment]
Yes, I'm pretty sure that also happens, but we haven't looked deeply into that. It could be interesting to see if highly conserved genes were not properly binned by Vamb (or other binners that uses depth like MaxBin, Canopy and MetaBAT) due to their abundances being thrown off.

**Comment by ntromas** [comment]
Hi,
Super interesting ! Naive question: I wonder if the nature of the samples would also have an impact, for example a time course study of the same sampling site. In that case, is co-assembly a better strategy that sample assembly?
