### ISSUE TITLE
binning using --aemb not working

### ISSUE THREAD

**Issue by kshitijtandon** [RasmussenLab/vamb#349]
Thank you for making such an amazing metagenome binning tool. 

I am trying to bin my samples using the **recommended approach** of mapping reads using _strobealign --aemb_ and obtaining sample specific __abundance.tsv__ files. This part works likes a charm. But when I try vamb (__version 4.3.1__) to bin, it throws error  __vamb: error: unrecognized arguments: bin default --aemb__ 

**Note: I am following workflow recommended [here](https://vamb.readthedocs.io/en/latest/how_to_run.html#quickstart)

If you can suggest a workaround, it will be great. Thanks.

**Comment by jakobnissen** [comment]
Dear @kshitijtandon 

This is a little embarassing, but the README and the documentation reflects the currently unreleased Vamb5, not the release Vamb 4.1.3.
We have recently created a proper documentation page, and so from Vamb 5 onwards, the default documentation will link to the latest release, and not to the unstable master branch.
You can find the correct README for Vamb 4.1.3 on the branch `release-4.1`: https://github.com/RasmussenLab/vamb/tree/release-4.1

**Comment by kshitijtandon** [comment]
Hi @jakobnissen 

Thanks for reply and explanation. Is the master branch still good to use until vamb5 is released ?

I was just able to get it work with --aemb and other parameters.

**Comment by kshitijtandon** [comment]
Hi @jakobnissen 

Thanks, it seems to work fine now.
