### ISSUE TITLE
hi! do you know what kind of problem is this?

### ISSUE THREAD

**Issue by aaa-meituo-aaa** [RasmussenLab/vamb#35]
(vamb) hsv709@pallas:/mibi/Wanli/test_recycler_scapp$ vamb --outdir vamb_out --fasta final.contigs.fasta --bamfiles sample1.bam -o C 

Traceback (most recent call last):
  File "/mibi/Wanli/anaconda/envs/vamb/bin/vamb", line 11, in <module>
    sys.exit(main())
  File "/mibi/Wanli/anaconda/envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 522, in main
    logfile=logfile)
  File "/mibi/Wanli/anaconda/envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 251, in run
    dropout, cuda, batchsize, nepochs, lrate, batchsteps, logfile)
  File "/mibi/Wanli/anaconda/envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 150, in trainvae
    logfile=logfile, modelfile=modelpath)
  File "/mibi/Wanli/anaconda/envs/vamb/lib/python3.7/site-packages/vamb/encode.py", line 465, in trainmodel
    raise ValueError('Last batch size exceeds dataset length')

ValueError: Last batch size exceeds dataset length

**Comment by jakobnissen** [comment]
Yeah. So the VAE doubles its mini batch size at the epochs given with the `-q` (default: `[25, 75, 150, 300]`). It uses a starting batch of 256 by default. So, at the 301st epoch, the batch size is 4096, which is larger than the number of observations you have.
You should probably not run Vamb if you have less than 4096 samples - see the warnings in the README.md. I would be careful when going below 50k samples.

**Comment by aaa-meituo-aaa** [comment]
> Yeah. So the VAE doubles its mini batch size at the epochs given with the `-q` (default: `[25, 75, 150, 300]`). It uses a starting batch of 256 by default. So, at the 301st epoch, the batch size is 4096, which is larger than the number of contigs you have.
> You should probably not run Vamb if you have less than 4096 contigs - see the warnings in the README.md. I would be careful when going below 50k contigs.

thanks!

**Comment by aaa-meituo-aaa** [comment]
> Yeah. So the VAE doubles its mini batch size at the epochs given with the `-q` (default: `[25, 75, 150, 300]`). It uses a starting batch of 256 by default. So, at the 301st epoch, the batch size is 4096, which is larger than the number of contigs you have.
> You should probably not run Vamb if you have less than 4096 contigs - see the warnings in the README.md. I would be careful when going below 50k contigs.

and another thing for "src/concatenate.py" script, if i install vamb by conda, where i can find this script

**Comment by nick-youngblut** [comment]
> You should probably not run Vamb if you have less than 4096 contigs - see the warnings in the README.md. I would be careful when going below 50k contigs.

I'm getting this too, and adaptively setting the vamb batch size for 100's of samples, depending on the number of contigs is a bit of a pain. Why not just include:

```
except ValueError:
    batch_size = number_of_contigs
```

so that the batch size cannot exceed the size of the input?

**Comment by jakobnissen** [comment]
If you have so few contigs that you see this error message (less than, say 4096), you should also add set the batch size and probably also reduce the network size anyway, or else you'll see bad fitting.

**Comment by nick-youngblut** [comment]
I see your point. I'll just add a pre-screen of my input. For example:

```
if [[ `grep -c ">" {input.fasta}` -lt 50000 ]]; then
  touch output.tsv   # create blank outputs
  exit 0
fi
```
