### ISSUE TITLE
import vamb

### ISSUE THREAD

**Issue by enryH** [RasmussenLab/vamb#38]
Just for checking my installation, I tried to import vamb (invoking the `__init__.py`) and got this error?

```python
>>> import vamb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vamb/vamb/__init__.py", line 30, in <module>
    from . import vambtools
  File "/home//vamb/vamb/vambtools.py", line 8, in <module>
    from vamb._vambtools import _kmercounts, _overwrite_matrix
ModuleNotFoundError: No module named 'vamb._vambtools'
```

I used conda. Is this problematic? The commandline interface itself, seems still to work, so I only want to report it briefly in case this might be an issue:)

**Comment by simonrasmu** [comment]
Hi Henry,

Yes please install with pip - I didn't have this problem with Conda though so we can look into it

**Comment by jakobnissen** [comment]
I think this happens because pip is set up to compile vambtools.pyx on installation. Maybe Conda doesn't do that?

**Comment by jakobnissen** [comment]
Closing this issue @enryH . You're welcome to re-open it if the issue was not resolved.

**Comment by Adarsh931** [comment]
I installed vamb using pip and got this error when running it:
`Traceback (most recent call last):
  File "/gpfs/ycga/project/christakis/as4258/conda_envs/vamb/bin/vamb", line 5, in <module>
    from vamb.__main__ import main
  File "/gpfs/ycga/project/christakis/as4258/conda_envs/vamb/site-packages/vamb/__init__.py", line 30, in <module>
    from . import vambtools
  File "/gpfs/ycga/project/christakis/as4258/conda_envs/vamb/site-packages/vamb/vambtools.py", line 8, in <module>
    from vamb._vambtools import _kmercounts, _overwrite_matrix
ModuleNotFoundError: No module named 'vamb._vambtools'
`
Please let me know how to resolve it.

**Comment by simonrasmu** [comment]
@jakobnissen

**Comment by jakobnissen** [comment]
@Adarsh931 I

t looks like the installation was not successful. During installation, `pip` (and also `conda`, as I've found out!) is supposed to use `Cython` to compile the `src/_vambtools.pyx` into `src/_vambtools.c`, which is then compiled to a binary in the `vamb` directory. Your message means the binary is not present. It's hard to debug without having the files, but you can try to check:
* Did `pip` report any errors on installation? For example, there could be linker issues, or Cython could work poorly
* Is there a binary file called something similar to `_vambtools[STUFF].so` (usually extension `.so`) in your `vamb/vamb` directory?

If there is no such file, you can try compiling the file manually and moving it into the `vamb/vamb` directory. Install Cython, then follow the instructions in the file `src/build_vambtools.py`.

Let me know how it goes!

**Comment by jakobnissen** [comment]
Closing this issue as resolved - if there are still problems, don't hesistate to re-open

**Comment by 2022wangg** [comment]
Dears,
@jakobnissen 
I have same problem with @Adarsh931. I have a file named "vambtools.py" in the vamb/vamb directory. Please let me what I should do next steps. Thank you.

**Comment by Adarsh931** [comment]
Hi,
Do you have the option to install with conda? If yes, conda installation works fine without any error.

**Comment by 2022wangg** [comment]
Yes, I used conda to install.
I have installed the vamb successfully.





发自我的iPhone


------------------ Original ------------------
From: Adarsh Singh ***@***.***&gt;
Date: Thu, Aug 25, 2022 4:35 PM
To: RasmussenLab/vamb ***@***.***&gt;
Cc: wangg ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [RasmussenLab/vamb] import vamb (#38)





 
Hi,
 Do you have the option to install with conda? If yes, conda installation works fine without any error.
