### ISSUE TITLE
VAMB expects same order of contigs in fasta file and contig-depth file, but does not complain if they do not match

### ISSUE THREAD

**Issue by microbiomix** [RasmussenLab/vamb#40]
Hi, I somehow generated a pair of fasta file and contig-depth file (latter from `jgi_summarize_bam_contig_depths`) where the contigs were not in the same order. Since the lengths matched, VAMB did not complain, but produced terrible bins - not a single one satisfying HQ MAG definition. When I reordered the inputs to match each other, then results were excellent as expected. It would be useful to get an error message in such scenarios. E.g., metabat2 complained that the order didn't match, which is actually how I figured out this was a problem. Without a comparison like this, I would have concluded that VAMB doesn't work well in that dataset, which is not at all true.
Best,
Mani

**Comment by jakobnissen** [comment]
Hello @microbiomix ! Glad to hear you got Vamb to work out.
You're right, Vamb ought to guard against mismatched references. In the just pushed commit, Vamb now compared the hashes of the references in the contigs and the ones in the JGI input file.

The master branch is not properly tested, though. I'll test it the coming days and create a new bugfix release.
Feel free to open another issue or ping me in this one if you think the solution is unsatisfactory.
