### ISSUE TITLE
New ML model for encoding

### ISSUE THREAD

**Issue by jakobnissen** [RasmussenLab/vamb#41]
VAEs are actually fairly bad at clustering. The problem is that the prior forces the contigs into one central group near the origin. Furthermore, it is disappointing that even though the VAE should first infer the genome from the contig and then sample a contig from the genome, it does not just return the inferred genome identity.
This is remedied in [Ge et al.'s elaborate dual AAE setup](https://www.ncbi.nlm.nih.gov/pubmed/31247579). 

Perhaps another model would be even more suitable. Pick a model that is fairly well established, *easy and stable to train*, and automatically clusters.

If the model requires you to specify the number of clusters beforehand, a generous estimate can be given. Only contigs with a high clustering identity threshold should be clustered (see Ge et al). In a second step, clusters representing half genomes can then be merged - this should be much easier than clustering contigs. We can also recruit the un-binned contigs with ordinary means like alignment.

**Comment by nick-youngblut** [comment]
You could possibly use a graphNN-based clustering method (eg., https://arxiv.org/abs/2006.16904) on a heterogeneous graph in which nodes=contigs and edges=[tnf similarity, coverage-across-samples similarity, taxonomic similarity, etc]

**Comment by jakobnissen** [comment]
After _extensive_ testing, we still don't have a model ready to replace the VAE.
This will not make it into the v4 release.
