### ISSUE TITLE
bin size extremely small

### ISSUE THREAD

**Issue by jianshu93** [RasmussenLab/vamb#52]
Dear author,

I have now successfully ran VAMB. However, most the bins generated are very small, 200k-1M, much smaller than those generated by multiple tools + DAStools strategy. How can that be complete considering such a small size (I have not run CheckM yet)? This is a sea water Metagenome. Do you have that issue for the gut dataset?

Thanks,

Jianshu

**Comment by simonrasmu** [comment]
Dear Jianshu, 

How many samples do you have and what are the sizes of the metagenomes? Vamb is only really better than other tools when you have multiple samples and run them combined.

**Comment by jianshu93** [comment]
Hello,
I actually ran them sample by samples as you introduced. I have a total of 20 samples. So basically it is better when doing something like co-assembly? But I do not want to do co-assembly. What's your suggestion ( I would try if it is not a coassembly but just do sample based assembly all together)?

Thanks.

Jianshu

**Comment by simonrasmu** [comment]
Dear Jianshu,

You don't want to do it sample by sample and you don't want to do it as a co-assembly. Instead:
1. Only include contigs >= 2000 bp in your assemblies.
2. Combine all assemblies to one file (and make sure config-naming is unique across samples)
3. Map reads to the combined assembly
4. Run Vamb with the 20 bam-files as input.

Step 1+2 can be done by `concatenate.py` (see the Readme on front page). Alternatively try the snakemake workflow, it will do everything for you.

Best,

Simon

**Comment by jianshu93** [comment]
Hi,

I successfully ran the Vamb using 20 bam input. However the output is kind of mess. Bins with name S11C45456.fna, I do not know which sample this bin belongs to. Is Vamb automatically sort input bam files by name? If so, I can just sort the input bam files and S11 will be the 11th sample?

Thanks,

Jianshu

**Comment by simonrasmu** [comment]
Great! 

Yes S11C45456 means Sample 11 Contig 45456. Sample 11 is the 11th sample that you input to concatenate.py. Pinging @jakobnissen to be absolutely sure.

Best,

Simon

**Comment by Shellfishgene** [comment]
Hi!

>     1. Only include contigs >= 2000 bp in your assemblies.

To compare VAMB with Metabat2 I set the `--minfasta` option to 2500, however this results in >34715 bins as opposed to Metabat2 with 641. I have a large co-assembled dataset. When you write to only include large contigs, does the assembly need to be filtered before mapping and running VAMB, or do you mean the `minfasta` option? Or would you just not recommend VAMB for co-assemblies?

**Comment by simonrasmu** [comment]
The `--minfasta` option specifies minimum size of output contigs. Instead to filter input contigs for 2500bp you want to use `-m 2500`

Best

Simon

**Comment by Shellfishgene** [comment]
Sorry, didn't read the manual properly. So `--minfasta 200000 -m 2500` would be similar settings to MetaBAT2 then.

Thanks!

**Comment by jakobnissen** [comment]
Dear @Shellfishgene 

See issue #4 . Vamb does create a huge number of small bins, because the program does not try to guess what kind of filter you want for your particular use case. Other binners create large amounts of small bins too, but usually tend to automatically filter away some of the bins. The issue with automatic filtering is that sometimes, you are actually looking for small bins.

And yes - `--minfasta 200000 -m 2500` should give the same filtering criteria as MetaBAT2 :)

Closing this issue as resolved, you are welcome to make another issue if you run into more problems
