### ISSUE TITLE
Add cuda check when --cuda is enabled

### ISSUE THREAD

**Issue by simonrasmu** [RasmussenLab/vamb#53]
Report in the beginning of the run if you try to run with --cuda enabled but torch cannot access cuda. Very simple just check

```
torch.cuda.is_available()
```

**Comment by jakobnissen** [comment]
That's already in `__main__.py`, during argument parsing:
```
if args.cuda and not torch.cuda.is_available():
        raise ModuleNotFoundError('Cuda is not available on your PyTorch installation')
```
Have you tried running it, where it didn't fail immediately?

**Comment by simonrasmu** [comment]
Ah ok, it was because Bent Petersen had issues with cuda, but they might caused from something else. Leaving it open a bit
