### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by ntromas** [RasmussenLab/vamb#55]
Hi,
First of all, thanks for this pretty nice pipeline! I am a bit confused with the outputs, especially the .tsv file. How can I get a fasta file for each bins? I am probably missing something but I can't find the vamb.vambtools.write_bins.py script (I used conda installation).

Would be great, to suggest post-processsing workflow to evaluate bins quality and profile their taxonomy for example.

Cheers,

Nico

**Comment by jakobnissen** [comment]
Dear @ntromas 

Thanks for the praise! To get an overview of the output, check the "Outputs" section of the README.me here on the GitHub page. If you have the original fasta file and the `clusters.tsv` output, you can convert it to fasta files using Vamb's internal functions. See the tutorial in `docs/tutorial.ipynb` (or the html file), in the section "posprocessing the clusters". If you know beforehand that you want to output fasta files, you should set the option `--minfasta` from command line.

In general, we should refrain from getting Vamb too involved in the post-processing step. I think it's a strength of Vamb that it's agnostic about the sources of the inputs (aligner, assembler, sequencer), and agnostic about the downstream analysis. We simply have no idea what our users are looking for, and so can't pre-empt it. For the same reason, we attempt to limit the amount of postprocessing in Vamb.

Closing this issue as solved, but you're welcome to re-open if you think I missed something, or make another issue.

**Comment by ntromas** [comment]
Thanks for the quick answer! The parameter --minfasta did the job!
I have some naive questions if that's ok...
I wonder why you would prefer using minimap2 instead of bowtie2?
For the --jgi parameters (depths) I guess, I just need to sort the bam files with samtools, right?
Last one, what is the advantage to concatenate the final contigs of multiples samples (and map the reads of these samples on that file) ?
Thanks a lot for your time!
