### ISSUE TITLE
Question about concatenate.py default settings

### ISSUE THREAD

**Issue by fnew** [RasmussenLab/vamb#58]
I ran concatenate.py on my 52 assemblies using: 'concatentate.py ms_catalog.fna.gz *contigs.fasta'. This produced a file with ~449,000 contigs. I then ran 'concatentate.py -m 2000 ms_catalog2.fna.gz *contigs.fasta' and got a file with ~1,274,000 contigs. I thought based on the help message that the default for -m is 2000, so I'm curious why I get such different results? (I'm using v3.0.2). Thank you!

**Comment by jakobnissen** [comment]
I can't reproduce this. Looking at the source code, `-m` does default to 2000. Try running it again.
