### ISSUE TITLE
error ValueError: Last batch size exceeds dataset length

### ISSUE THREAD

**Issue by karinedurand** [RasmussenLab/vamb#59]
Hi,
I run vamb as recommanded : TL;DR: Here's how to run Vamb
All is fine except with vamb --outdir outdir --fasta catalogue.fna.gz --bamfiles *.bam  -o C --minfasta 200000
[E::idx_find_and_load] [E::idx_find_and_load] Could not retrieve index file for 'Y72.bam'
ValueError: Last batch size exceeds dataset length
I try to install the snakemake workflow but with
/mamba  install -n vamb -c bioconda minimap2 pysam checkm-genome
Encountered problems while solving.
Problem: nothing provides zlib 1.2.8* needed by pysam-0.14.0-py27_htslib1.7_0
Do you know how solved it ?
Best
Best

**Comment by simonrasmu** [comment]
Dear Karine,
I am not 100% sure about that error, but are you sure that you map the bam-files to the same catalogue (ie. that they contain the same contigs)? Can you post your workflow?

With regards to using conda it can be a pain to get it working as different versions of python have different dependencies available. Try to upgrade to another python and it could work. 

Best,

Simon

**Comment by karinedurand** [comment]
thanks
Here my worflow :
First I assemble each sample Y67 and Y72 with spades.py --meta (rename contig with number)
2- concatenate the 2 contigs.fasta with concatenate.py (Y67contigs.rename.fasta and Y72contigs.rename.fasta)
3-minimap2 -d catalogue.mmi catalogue.fna.gz; # make index
sample1 : minimap2 -t 8 -N 50 -ax sr catalogue.mmi Y67.unmappedVS.1.fq.gz  Y67.unmappedVS.2.fq.gz | samtools view -F 3584 -b --threads 8 > Y67.bam
sample 2 : minimap2 -t 8 -N 50 -ax sr catalogue.mmi Y72.unmappedVS.1.fq.gz  Y72.unmappedVS.2.fq.gz | samtools view -F 3584 -b --threads 8 > Y72.bam
4-vamb --outdir outdir --fasta catalogue.fna.gz --bamfiles *.bam -o C --minfasta 200000
Best 
Files are in [[])](https://filesender.renater.fr/?s=download&token=ef55c7a7-aec3-42eb-933d-2b2551ed3da0)

**Comment by simonrasmu** [comment]
Can you post the log-file output from Vamb (if it starts to make one)?

**Comment by karinedurand** [comment]
[log.txt](https://github.com/RasmussenLab/vamb/files/5958889/log.txt)

**Comment by simonrasmu** [comment]
Thanks - this looks like you have a very small dataset (only 6.6 Mbp from 2 samples). Could you upload the data somewhere for us to see what is going on?

**Comment by karinedurand** [comment]
yes and workflow snakemake is running with the same issue see log file 
All files are in  https://filesender.renater.fr/?s=download&token=ef55c7a7-aec3-42eb-933d-2b2551ed3da0
[2021-02-10T160638.362713.snakemake.log](https://github.com/RasmussenLab/vamb/files/5959015/2021-02-10T160638.362713.snakemake.log)

**Comment by simonrasmu** [comment]
Dear Karine, 

Thank you - I took a look at it. The problem is that you have very few contigs after filtering for 2kbp. That is the reason that Vamb failed. You can run it by setting a lower batch size. E.g.

vamb  --fasta catalogue.fna.gz --bamfiles Y67.bam Y72.bam --outdir vamb -t 64 -o C --minfasta 200000

Not sure the output will make sense though as we never tried Vamb on so few contigs. It might be better to just run Vamb on each sample separately.

Best,

Simon

**Comment by karinedurand** [comment]
thanks a lot
Best,
Karine
