### ISSUE TITLE
rpkms.shape[1] error in VAMB Snakemake workflow

### ISSUE THREAD

**Issue by Mew233** [RasmussenLab/vamb#60]
Hi, 
I have an issue when I run snakemake VAMB3.0.2. It seems there is a problem in running vamb. I attached error message from log/vamb as below. It seems rpkm does not exit, I am not sure why. The steps before vamb looks fine. 
Thanks for your help in advance!

---------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/gpfs/ycga/project/christakis/cx79/conda_envs/vamb/bin/vamb", line 8, in <module>
    sys.exit(main())
  File "/gpfs/ycga/project/christakis/cx79/conda_envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 528, in main
    logfile=logfile)
  File "/gpfs/ycga/project/christakis/cx79/conda_envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 251, in run
    dropout, cuda, batchsize, nepochs, lrate, batchsteps, logfile)
  File "/gpfs/ycga/project/christakis/cx79/conda_envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 134, in trainvae
    nsamples = rpkms.shape[1]
IndexError: tuple index out of range

**Comment by jakobnissen** [comment]
That's strange. It appears your `rpkms` is a vector, where it should be a matrix. Can you post the logfile (`log.txt`)?

**Comment by Mew233** [comment]
When I run snakemake, since vamb encounters problem, it automatically deletes output files of "failed job vamb since they might be corrupted vamb/lengths.npz, vamb/log.txt, vamb/tnf.npz".

So I run this command line by myself: 
vamb --outdir vamb --fasta contigs.flt.fna.gz --jgi jgi_matrix/jgi.abundance.dat -o C -m 2000 --minfasta 500000 2>log/vamb/vamb.log

The log.txt is shown as below
----------------------------------------------------------------------------------------------------------------
Starting Vamb version 3.0.2
        Date and time is 2021-03-03 13:57:25.637086

Loading TNF
        Minimum sequence length: 2000
        Loading data from FASTA file contigs.flt.fna.gz

        Kept 103488555 bases in 14028 sequences
        Processed TNF in 3.64 seconds

Loading RPKM
        Loading RPKM from JGI file jgi_matrix/jgi.abundance.dat
        Processed RPKM in 0.04 seconds

Creating and training VAE

**Comment by jakobnissen** [comment]
Finally found the issue. It's been fixed on the master branch. Try upgrading to master and see if it works.

**Comment by Mew233** [comment]
Thank you so much!!! It works now.

**Comment by SilasK** [comment]
Could we have a new release with this solution, please? For the integration in pipeline, I prefer to rely on conda packages.
