### ISSUE TITLE
Recommended workflow breaks for large dataset (no SQ lines in the header when converting to bam)

### ISSUE THREAD

**Issue by zeqianli** [RasmussenLab/vamb#63]
Hi, for large datasets, the recommended workflow breaks at this step: `samtools view -F 3584 -b --threads 8 > sample1.bam`. Error message: 
```
samtools view: error reading file "sample1.sam"
[E::sam_parse1] no SQ lines present in the header
```

I'm working on a large dataset (288 samples, from https://www.nature.com/articles/s41586-018-0386-6). The error only happens when I run the recommended workflow on the entire dataset, but running on subsets of a few samples was fine. 

I believe the problem is: for large datasets, a huge .mmi index file was produced (14.3G in my case). According to https://github.com/lh3/minimap2/issues/37#issuecomment-336998722, for reference files larger than 8G, minimap2 create a multi-part index and output no SQ lines for sam files (minimap2 shows error messages about this: 
`[WARNING][1;31m Indexing parameters (-k, -w or -H) overridden by parameters used in the prebuilt index.[0m
[WARNING][1;31m For a multi-part index, no @SQ lines will be outputted. Please use --split-prefix.[0m.` Then converting them to bam breaks.

This is not a problem on Vamb and should be an easy fix, but I'm naive on alignment tools. Can you suggest a fix? And may I suggest adding documentations to the recommended workflow?

**Comment by jakobnissen** [comment]
Yeah we are, unfortunately, aware of that *absolutely horrifying bug* in minimap2. The workaround is to either increase the memory consumption of the minimap2 index (e.g. `-I 64g`), if you have access to a machine with lots of RAM, or alternatively to use another aligner.

I've just updated the README to mention the bug in `minimap2`.

**Comment by zeqianli** [comment]
Thanks! I was able to get this working. I want to comment this in case others see the post: the `-I` tag is needed at both the indexing step and the alignment step: 
```
minimap2 -I 32g -d catalogue.mmi /path/to/catalogue.fna.gz; # make index
minimap2 -I 32g -t 8 -N 50 -ax sr catalogue.mmi /path/to/reads/sample1.fw.fq.gz /path/to/reads/sample1.rv.fq.gz | samtools view -F 3584 -b --threads 8 > /path/to/bam/sample1.bam

```
`-I` tag at the second step alone will not work. See https://github.com/lh3/minimap2/issues/15#issuecomment-324842627. 

I'm closing the issue.
