### ISSUE TITLE
vamb version and minfasta

### ISSUE THREAD

**Issue by nselem** [RasmussenLab/vamb#67]
Hello I installed vamb by conda and it does not have the minfasta parameter. Then I searched for the vamb version and I was unable to find it. 

This  is my metagenomics.yml file:
name: metagenomics                                                                
dependencies:                             
  - megahit              
  - kraken2 
  - krona             
  - maxbin2
  - taxonkit
  - quast
  - spades
  - kraken-biom
  - checkm-genome
  - vamb 
Then I run  
conda env create -f metagenomics.yml
conda activate metagenomics
vamb --outdir 01/ --fasta 01_scaffolds.fasta --bamfiles 01.bam --minfasta 200000
And I got this error
usage: vamb outdir tnf_input rpkm_input [options]                                                                                     vamb: error: unrecognized arguments: --minfasta 200000 

On the othe side when I installed vamb with pip3 I got the version vamb-3.0.2  and in this case there is the minfasta parameter available. Is it possible to fix this when installing by conda?

**Comment by simonrasmu** [comment]
Sometimes when installing from conda it depending on the python version pulls an old version of vamb (2.something). I have tried to see if I could fix this, but to no avail. If you want to install from conda you can  try to update your python - otherwise just use the pip-version.

Best,

Simon

**Comment by simonrasmu** [comment]
Closing issue as no update since April
