### ISSUE TITLE
coverage RPKM not reliable for conservative contigs like 16S

### ISSUE THREAD

**Issue by jianshu93** [RasmussenLab/vamb#68]
Dear Vamb Team,

I am writing to suggest a new way of calculating coverage depth for each contig, called truncated mean depth 80%. For each contig, there might be conservative regions like 16S, when calculating the cover depth of this contig, a lot of short reads from 16S conservative regions of other genomes may also be mapped to this contig and thus overestimation of coverage depth for this contig. This could interfere with binning process. We should remove 10% top mapped positions and bottom 10% percent mapped positions before calculating the coverage depth of each contig to mitigate the effect of conservative regions. See the trimmed mean depth method fo calculate contig coverage depth in CoverM for detail.

Thanks,

Jianshu

**Comment by simonrasmu** [comment]
Dear Jianshu,

Thanks for the suggestion! Do you have any experience in that using this improves binning in general or only binning of the 16S regions? We are currently re-writing parts of VAMB to use CoverM for calculating the depth of each contig so it would be easy to achieve. @Paupiera @jakobnissen

**Comment by jakobnissen** [comment]
I completely agree that we should do this, and that we should migrate to CoverM.

**Comment by jianshu93** [comment]
Our team at Georgia Tech has a lot of experience in calculating coverage depth, a method called TAD80 (truncated mean depth 80%), which removes top 10% and bottom 10% of positions in terms of coverage depth for each contig, is thought to be more reliable than RPKM because it takes into account edge effects for reads mapping and also conserved regions like 16S. Both Kenji (https://github.com/KGerhardt) and Roth (https://github.com/rotheconrad) could help.

Jianshu

**Comment by jakobnissen** [comment]
This is fixed in version 4, where depths is estimated by first removing the terminal 75 bp, then using TAD80.
