### ISSUE TITLE
Running Vamb on large multivariate dataset

### ISSUE THREAD

**Issue by GeoMicroSoares** [RasmussenLab/vamb#69]
Hi there,

Congratulations for this tool first of all! 
I'm interested in running Vamb for a large dataset I've gathered that includes samples from relatively different ecosystems that although sharing some MAGs I'm interested in in principle, should have quite disparate compositions. How would you suggest running Vamb under these conditions? What parameters should I pay attention to specifically and what values would you recommend setting for optimal performance for this case?

Thanks in advance!

**Comment by simonrasmu** [comment]
Hi GeoMicroSoares,

Thank you very much.

If you are interested in MAGs across the dataset then I would run VAMB with all files as input. This should work well and give you clusters across all datasets. An alternative is to run separately on the samples for each disparate dataset and then compare what you get, but it is not necessarily going to be better.

For parameters I would just run with default parameters, but you can achieve more near complete MAGs if you run VAMB with different sizes of the networks (see example on the README) and then use dRep with high identity threshold to combine the datasets.

Best,

Simon

**Comment by GeoMicroSoares** [comment]
Cheers Simon, thanks for the tips, will try and report back ASAP on how this compares with the run under default settings.

**Comment by GeoMicroSoares** [comment]
Hey again @simonrasmu , ran a couple of iterations of what's suggested in the website and currently comparing that to previous results other people got previously with DAS_Tool ran with a couple other binners. Do you think this could be improved at all with a couple more changes to the parameters?

![image](https://user-images.githubusercontent.com/14272488/117123933-f52d8480-ad97-11eb-9923-f8fa122f81e1.png)
![image](https://user-images.githubusercontent.com/14272488/117123941-f959a200-ad97-11eb-93bb-bee5c2b982cb.png)

**Comment by simonrasmu** [comment]
Hi Andres,

Did you have a look at the number of near-complete bins? It is difficult to assess from the plots (overplotting for the first and density in the lower). 

Then, what you can do is to run dRep or galah on combined bin sets per sample. In this way you get the best bin (based on Completeness and Contamination from checkM). We have a paper on the way using this approach and that can net you an extra 10-15% NC bins (on the datasets that we tested on).

Best,

Simon

**Comment by GeoMicroSoares** [comment]
Hey again @simonrasmu ,

Here's another plot which shows any bins > 70% complete and <10% contaminated and their numbers along the parameter changes I've tried.

Think this dataset would benefit from further tinkering with Vamb parameters?

![image](https://user-images.githubusercontent.com/14272488/117150223-3df53580-adb8-11eb-917b-1a7dda53524e.png)

Will definitely give dRep/galah a try ASAP and would appreciate any tips to recover those extra 10-15% NC if that's possible at all atm!

**Comment by simonrasmu** [comment]
Thanks! Interesting that VAMB gives worse(?) results compared to DAS_Tool. Did you run Vamb in the multi-split mode (e.g. cat all contigs together and bin that). How different are the communities? Could potentially be an issue with that (e.g. better running VAMB for each community).

**Comment by GeoMicroSoares** [comment]
I followed the instructions [here](https://github.com/RasmussenLab/vamb#tldr-heres-how-to-run-vamb) - so yes, all contigs were concatenated using your script, then mapped reads to that and ran VAMB as above... This is what you mean right? 

They're 2 sets of samples from different sites... Wouldn't running VAMB for each sample lose on retrieved MAG quality/number?

**Comment by simonrasmu** [comment]
And you used `-o C` when running VAMB (assuming you used the concatenate script). How many samples do you have? I suggest to run on the two sets separately, not sample by sample.

**Comment by GeoMicroSoares** [comment]
Hey again. - * facepalm * nope, none of those were run using `-o C`, think an error popped up because of something else two days ago and dropping that and probably something else made it work so continued without it... Will re-run this and get back to you. Thanks again!

**Comment by simonrasmu** [comment]
Ok - let us know if you have problems running the `-o C`. The point of that it is to split the clusters into per-sample bins where it assumes that contig-names and samples are separated by a "C".  For instance your contigs should be named as below where S1 and S2 are sample names and C1-C3 are contig numbers. This is literally what the concatenate script does for you (plus filtering for contig length)

S1C1
S1C2
S1C3
S2C1
S2C2
etc

This should greatly improve the number of near complete bins coming out of the analysis.

**Comment by simonrasmu** [comment]
Very nice that it is better, but quite interesting that it is not better than DasTool - we haven't seen that before. Anyway, I think you should definitely try to combine MAGs by running dRep (and it will be interesting to see how much the VAMB bins overlap with the DasTool bins).

**Comment by GeoMicroSoares** [comment]
Hey again @simonrasmu well I guess this is Vamb ran on multiple samples, all at once and DAS_Tool and the other binners we used ran on each sample at a time. I guess that will make a difference too! You mean running `dRep dereplicate` btw right?

**Comment by GeoMicroSoares** [comment]
Hi again @simonrasmu , just wondering here - I'd like to replicate your VAMB+MetaBAT2+DAS_Tool benchmarks in my data. Since Vamb calculates abundance data by itself, did you use that as input for MetaBAT2 as well or just ran it as default?

**Comment by simonrasmu** [comment]
Hi @GeoMicroSoares,

We ran MetaBAT2 using the default settings and using the contig catalogue as input (@jakobnissen correct me if I am wrong here).

Best,

Simon
