### ISSUE TITLE
Hyperparameters of iterative medoid in VAMB

### ISSUE THREAD

**Issue by zpf0117b** [RasmussenLab/vamb#71]
Hi there,

I found five hyperparameters at the head of the code in vamb/cluster.py
```
_DEFAULT_RADIUS = 0.06
_MEDOID_RADIUS = 0.05
_DELTA_X = 0.005 
_XMAX = 0.3
_NORMALPDF = _DELTA_X * _torch.Tensor(
      [2.43432053e-11, 9.13472041e-10, 2.66955661e-08, 6.07588285e-07,
       1.07697600e-05, 1.48671951e-04, 1.59837411e-03, 1.33830226e-02,
       8.72682695e-02, 4.43184841e-01, 1.75283005e+00, 5.39909665e+00,
       1.29517596e+01, 2.41970725e+01, 3.52065327e+01, 3.98942280e+01,
       3.52065327e+01, 2.41970725e+01, 1.29517596e+01, 5.39909665e+00,
       1.75283005e+00, 4.43184841e-01, 8.72682695e-02, 1.33830226e-02,
       1.59837411e-03, 1.48671951e-04, 1.07697600e-05, 6.07588285e-07,
       2.66955661e-08, 9.13472041e-10, 2.43432053e-11])
```
Here are my questions.
What should be mentioned while I tune these parameters?
How do they influence the final result respectively or jointly?
I got far fewer clusters than the original architecture when changing the VAE to other encode models. For example, I tried the airway dataset and got at most 700 clusters and bins while VAMB got 84502 clusters. I know it's not necessary to get more and more clusters, but it's still necessary to get more than 900 clusters. I wonder how we tune these parameters to get more clusters.

**Comment by simonrasmu** [comment]
Hi zpf0117b,

Those parameters are tuned to work with the latent space coming out of the VAE implemented in VAMB. They might work using other latent spaces, but for instance on the raw data they do not perform well. You could try changing the default and medoid radius, delta_x and xmax, but it will difficult to predict which changes will give better parameters. An alternative is to use k-means clustering - we tried this in the paper and it works reasonably well (see Supplementary Figure 16). We used minibatch k-means implemented in scikit-learn: ‘MiniBatchKMeans (n_clusters=750, random_state=0, batch_ size=4096, max_iter=25, init_size=20000, reassignment_ratio=0.02)’.

Best,

Simon

**Comment by zpf0117b** [comment]
Thank you simonrasmu, I got it. 
Closed this issue.
