### ISSUE TITLE
Can vamb be used for metatrascriptomic data

### ISSUE THREAD

**Issue by zhaoxvwahaha** [RasmussenLab/vamb#75]
Hi,

Can vamb be used for metatrascriptomic data? My goal is identifying different contigs from a RNA virus from metatrascriptomic data.
How to just use the nucleotide frequency to do bin if I have no coverage information?

Thanks in advance

**Comment by jakobnissen** [comment]
We don't know, really! It _probably_ will work well, but we haven't tested it.
I wouldn't recommend using Vamb without coverage information. If it possible, but the results will almost certainly be worse than if you use a kmer-based tool like Kraken. See also #18.

Closing as resolved. You're welcome to re-open it if you have more questions.
