### ISSUE TITLE
Which clusters belong to the same mega-cluster?

### ISSUE THREAD

**Issue by SilasK** [RasmussenLab/vamb#78]
Hey, I'm trying out vamb. As I understand the idea of using multisplit or co-binning is that you create mega-clusters of contigs that belong to the same (sub-)species but then you split the mega-cluster into bins according to the sample of origin. 

I wonder if the information of the original mega-cluster, e.g. the same species. can be found somewhere in the output?

Also, do you think making a re-assembly of all the reads mapping to a mega-cluster could be a good idea? All the reads from all samples or maybe all the read from one sample.

**Comment by jakobnissen** [comment]
You should be able to see this in the sequence headers. I can't remember the format exactly, but I think it may be e.g. `S1C1` for sample 1, cluster 1. The cluster are the pre-split bins.

**Comment by SilasK** [comment]
Obviously. The format depends on the split character used. I mistook the cluster names as contig names.
