### ISSUE TITLE
Run with GPU

### ISSUE THREAD

**Issue by kodragonP** [RasmussenLab/vamb#82]
This is my command: 
vamb --minfasta 200000 -l 24 -n 384 384 --outdir TC87O1-gpu --cuda --fasta TC87O1.fasta --jgi TC87O1_depth.txt
This is error: 
terminate called after throwing an instance of 'std::runtime_error'
  what():  generic_type: cannot initialize type "WorkerId": an object with that name is already defined
Aborted

**Comment by simonrasmu** [comment]
Hi kodragonP,

I have no clue about this error - does it work/run if you run it without GPU (e.g. remove `--cuda`)?

**Comment by kodragonP** [comment]
It work well without GPU, except print endless WARMING.

I created a new conda environment (python=3.7), and run pip install https://github.com/RasmussenLab/vamb/archive/3.0.2.zip
Error is no cuda installed.
Then I install pytorch-gpu using conda, the above error reported.

**Comment by simonrasmu** [comment]
From looking at the error it looks like something to do with pytorch. Can you install pytorch using pip instead (I remember we had issues with pytorch-gpu from conda)

**Comment by kodragonP** [comment]
**I installed torch just now with pip.**
(Vamb) [root@localhost vamb_binning]# pip install torch torchvision
Requirement already satisfied: torch in /root/miniconda3/envs/Vamb/lib/python3.7/site-packages (1.9.0)
Requirement already satisfied: torchvision in /root/miniconda3/envs/Vamb/lib/python3.7/site-packages (0.10.0)
Requirement already satisfied: typing-extensions in /root/miniconda3/envs/Vamb/lib/python3.7/site-packages (from torch) (3.10.0.1)
Requirement already satisfied: pillow>=5.3.0 in /root/miniconda3/envs/Vamb/lib/python3.7/site-packages (from torchvision) (8.3.1)
Requirement already satisfied: numpy in /root/miniconda3/envs/Vamb/lib/python3.7/site-packages (from torchvision) (1.21.2)

**Reported error:**
(Vamb) [root@localhost vamb_binning]# vamb --outdir S --fasta TC87O1.fasta --jgi TC87O1_depth.txt --minfasta 200000 --cuda -m 2000 -l 32 -n 512 512
Traceback (most recent call last):
  File "/root/miniconda3/envs/Vamb/bin/vamb", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/Vamb/lib/python3.7/site-packages/vamb/__main__.py", line 448, in main
    raise ModuleNotFoundError('Cuda is not available on your PyTorch installation')
ModuleNotFoundError: Cuda is not available on your PyTorch installation

**Comment by simonrasmu** [comment]
So the problem is your cuda drivers or the card. Pytorch is clearly not able to access cuda with your GPU

**Comment by kodragonP** [comment]
The problem solved after reinstalling GPU driver. Thank you!

**Comment by simonrasmu** [comment]
Great!
