### ISSUE TITLE
Separator 'C' not in sequence label: 'scaffold_24892

### ISSUE THREAD

**Issue by xushaoyi** [RasmussenLab/vamb#84]
Dear author, I used vamb to doing the binning procedure, and got a error like this, do you have any idea how to solve it? thanks!

  File "/home/dell/lib/miniconda2/envs/vamb/lib/python3.7/site-packages/vamb/vambtools.py", line 608, in _split_bin
    raise KeyError("Separator '{}' not in sequence label: '{}'".format(separator, header))
KeyError: "Separator 'C' not in sequence label: 'scaffold_24892'"

**Comment by jakobnissen** [comment]
Yes - you likely passed in `-o C` to Vamb. This enables binsplitting. By passing in `C`, you say that your contigs are formatted as `{SAMPLE}C{CONTIG}`, but there was no "C" in your contig names.
