### ISSUE TITLE
incorrect version label (v3.0.3) in workflow readme

### ISSUE THREAD

**Issue by yanhui09** [RasmussenLab/vamb#85]
It's a small things. 
Install vamb 3.0.3 through pip shall be:
```
pip install https://github.com/RasmussenLab/vamb/archive/refs/tags/v3.0.3.zip
```
`v` is missing there, you probably labeled it as `v3.0.3` rather than `3.0.3`

**Comment by simonrasmu** [comment]
Fixed now - thanks!
