### ISSUE TITLE
Multi-split binning and long-read assemblies

### ISSUE THREAD

**Issue by Vini2** [RasmussenLab/vamb#86]
Hi vamb developers,

I wanted to ask about the multi-split binning mode (using "binsplit separator") and long-read assemblies. As I understood, this mode separates contigs from different samples and shares them across the final bins generated. I have the following concerns;

1. Species found across different samples are treated as different strains. Although this does not affect the CheckM results this can certainly result in a higher duplication ratio if the same species/strain is present in multiple samples. Without any other post-processing, how would this issue be addressed? I can see that you suggest using DASTool in this issue #72. Would there be any other alternatives?

2. In some cases, it is essential to combine multiple samples when there is a higher number of species with vastly varying coverage across samples. Would you still suggest using multi-sample assembly? Real datasets (For example [COPD](https://www.ncbi.nlm.nih.gov/bioproject/?term=PRJEB9034) and [G_DNA_Tongue dorsum](https://www.ncbi.nlm.nih.gov/sra/?term=SRR1031078)) may have multiple small samples. In that case, would it be more appropriate to pool and assemble after which abundance information can be evaluated separately using reads from the individual samples? (In my experience, pooled assemblies from tools such as metaSPAdes have higher-quality assemblies for such real datasets). I really appreciate if you can provide some suggestion/feedback regarding this that I may have overseen.

3. We have an increasing interest in long-read assemblies for which the number of contigs is much less (with increasing NGA50). In such cases how would we adopt VAMB? 

I look forward to running VAMB. :) 

Thanks in advance for your support regarding this.

Best regards,
Vijini

**Comment by simonrasmu** [comment]
Dear Vijini,

I think you got the multi-split binning mode opposite? Multi-split binning combines contigs from all samples and clusters all contigs simultaneously. Each of the clusters then contain all contigs that were binned together across all samples and these are then split, per original sample, to per-sample bins. Therefore multi-split binning takes advantage of binning all the contigs together and produces per-sample representation of each bin. It does not generate cross sample chimeras (as opposed to pooled assembly).

1. I am not sure I understand this question, organisms found across different samples will go in the same cluster, but separate bins.
2. I am not a fan of pooled assembly, it generates chimeras that for sure does not exist in nature - however, you can try it out and see if it helps you getting good recovery of certain strains you are interested in. 
3. VAMB should also work fine with long-read assemblies. The main issue here can be the abundance estimation (if you don't have Illumina reads) where I am not sure how it will affect the binning, but it is something we will test in the near future.

Best,

Simon

**Comment by Vini2** [comment]
Dear Prof Rasmussen,

Thank you very much for your reply. I think I have the correct understanding and now I understand very clearly (point 1).

I appreciate your time in replying me. As this was very useful and clarified my doubts, I will close the issue. 

Best regards,
Vijini
