### ISSUE TITLE
undefined symbol: __intel_cpu_feature_indicator error

### ISSUE THREAD

**Issue by dot4822** [RasmussenLab/vamb#93]
To whom it may concern,

I am trying to install VAMB on the HPC cluster of university.

To install VAMB with GPU support, the command lines I used are as below:

```
conda create -n vamb python==3.7
conda activate vamb
pip install https://github.com/RasmussenLab/vamb/archive/v3.0.3.zip
```

It works well until I run `vamb` to check the installation.

The error information is as below:

```
Traceback (most recent call last):
  File "/storage/miniconda3/envs/vamb/bin/vamb", line 5, in <module>
    from vamb.__main__ import main
  File "/storage/miniconda3/envs/vamb/lib/python3.7/site-packages/vamb/__init__.py", line 30, in <module>
    from . import vambtools
  File "/storage/miniconda3/envs/vamb/lib/python3.7/site-packages/vamb/vambtools.py", line 8, in <module>
    from vamb._vambtools import _kmercounts, _overwrite_matrix
ImportError: /storage/miniconda3/envs/vamb/lib/python3.7/site-packages/vamb/_vambtools.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __intel_cpu_feature_indicator
```

After this, I tried to install VAMB via BioConda, and it worked.

As I am still keen to try VAMB with GPU support, I wonder whether there is a fix for this error.

Thanks for your time

Best wishes,
Dot

**Comment by jakobnissen** [comment]
I'm closing this, as it doesn't seem like an issue on the Vamb side.
