### ISSUE TITLE
Question about bin similarity

### ISSUE THREAD

**Issue by Laura-Alex** [RasmussenLab/vamb#97]
Hello,

First of all, thank you for your work. I've had quite good results with vamb and it is really straightforward to use.

Secondly, I was wondering how to interpret the phylogenetic distances between bins. I assume that S5C4951, for instance, means 'sample #5, cluster #4951'. Which would make S2C4951, I assume, a very similar (potentially identical?) bin, simply from another sample, is that correct? But what about similar bins from the same sample? I guess I'm mostly wondering, how similar can something be while remaining a different cluster/bin? Are we talking species/subspecies/isolates? I've used the standard vamb workflow (https://github.com/RasmussenLab/vamb) except for assembling with MEGAHIT.

Thank you for your time!

**Comment by jakobnissen** [comment]
Hi, and thanks for the kind words!

Good question. In general binners (and especially deep learning based ones!) are a bit of a black box, where neither I nor anyone else really can give any guarantees as to how it will behave for any particular cluster.

You're right that S1C2 means sample 1, cluster 2, and that the same cluster in different samples tend to be very different. How different? I seem to recall it would begin to cluster organism together at around 98% nucleotide identity in our tests, but I'm sure it depends on a lot of stuff like the sample diversity and the precision of the mapping. At any rate it's a statistical thing: There will be lots of clusters that contain contamination from organisms that are way more different than 2% nt difference.

At the end of the day, it is primarily the mapping step that determines how fine-grained the binning will be. If your mapping process has a lot of cross-mapping between contigs that are only 90% identical, Vamb will not be much better than that.

**Comment by Laura-Alex** [comment]
`the same cluster in different samples tend to be very different`

Interesting! I was not expecting this.

The samples I'm working with are quite diverse. That probably affects things. I guess I got a lot of high-quality bins containing my genes of interest, so it becomes necessary to figure out which are representative / distinct enough from the rest to use in future analyses (e.g. phylogenomics). I have to say it's a much better problem to have than the opposite!

Thank you for your explanation. I guess with some things there's no simple answer, but that's fine. Now that can plan what to do next : )
