### ISSUE TITLE
In which order are sample names determined?

### ISSUE THREAD

**Issue by Laura-Alex** [RasmussenLab/vamb#98]
Originally I expected samples to be numbered (e.g. S1, S2...) in an order that reflects the original files' names (which in my case are SRA accessions). But I found a bin associated with a sample number that is mildly unexpected, and thought to check my assumption. In the log file, for instance, under 'order of columns', there are two text blocks. The first one has the names in the expected order, but not so for the second. For example:

```
Order of columns is:
        /username/vamb/location/bam/SRR_822.bam
        /username/vamb/location/bam/SRR_890.bam
        /username/vamb/location/bam/SRR_893.bam
        /username/vamb/location/bam/SRR_895.bam
        /username/vamb/location/bam/SRR_896.bam
        /username/vamb/location/bam/SRR_906.bam

        Processed /username/vamb/location/bam/SRR_890.bam
        Processed /username/vamb/location/bam/SRR_893.bam
        Processed /username/vamb/location/bam/SRR_895.bam
        Processed /username/vamb/location/bam/SRR_822.bam
        Processed /username/vamb/location/bam/SRR_896.bam
        Processed /username/vamb/location/bam/SRR_906.bam
```

What I imagine could have happened is that smaller files were processed first, and therefore received smaller sample numbers. Is this possible? If not, is there a way to check which files were associated with each sample number?

I thought I'd check the technical aspects before investigating it as a biological effect.

Thank you for your time!

**Comment by jakobnissen** [comment]
Dear @Laura-Alex 

The column order is as specified in the first block. The second block just says which order the files finished processing in, which, as you note, may not be the same order as the jobs were launched in. The finishing order should not affect the column order.
Closing this as solved - but if you find out that I messed up somewhere and the column got permuted (unlikely as it seems), please re-open and I'll fix it!

**Comment by chassenr** [comment]
@jakobnissen I have a similar issue. The samples names used by VAMB do not correspond to the column order specified by the log file (or to the order of processing). I am now individually grep-ing for the contig names in all assemblies to reconstruct the correct order... Do you have any idea what may have happened there? 

Thanks!

Cheers,
Christiane

**Comment by jakobnissen** [comment]
@chassenr I don't quite understand what you mean. Vamb does not store the sample names anywhere, only the order. Do you mean that the order listed in the log file is not actually the same as the order of the columns of the RPKM matrix?

**Comment by chassenr** [comment]
I am not familiar with the output format of the RPKM matrix (and for someone who is mainly coding in R, the python documentation that you linked in the README was not straightforward), so I did not look at this file yet. I am trying to assign the bins generated by VAMB to the samples that the contigs originated from. For this, I was using the information in the log file provided in order of columns, assuming that this order would translate to S1...N. This is not the case.

**Comment by chassenr** [comment]
Not really... I am aware of the naming convention. 

I am using -o C, so my contig names are e.g. >S22CNODE_14264_length_4169_cov_4.008906, etc. and the bin name would be e.g. S22C3253.fna. I now need to know which original sample name S22 corresponds to. I was hoping to use the order of columns in the log file, but this order is incorrect. As a solution, I am now using grep on the contig names (minus of course the S22C in this example) to search the assemblies of all my samples for those contigs. Is there an easier way to identify which original sample names the S1...N correspond to?

**Comment by jakobnissen** [comment]
Oh, I see - you are using the Snakemake workdlow? In that case, it comes from the list of files in the `contigs.txt` file you provided to the workflow.

**Comment by chassenr** [comment]
I am running VAMB within a snakemake workflow, but one that I built myself where VAMB is only one step in a larger worflow that goes from read trimming to assembly to binning to bin reassembly and annotation. In case you are curious: https://git.io-warnemuende.de/bio_inf/workflow_templates/wiki/metaG_Illumina_PE

I only realized that you also offer a snakemake version after I already had my scripts running. Sorry for that. Interestingly, even though I am not using your snakemake implementation (and also don't provide a contigs.txt or samples2data.txt file), the manual check I did with grep revealed that VAMB was actually using the order of samples that I specific as input to my snakemake workflow. I never expected this to be the case and I was confused when the order of columns in the VAMB log file showed something different.

Sorry, if I caused any undue confusion and thanks a lot for your prompt replies.

**Comment by jakobnissen** [comment]
No worries. I'm still confused on one point: If you're not using the Vamb Snakemake workflow, how do you then rename the contigs so they're suitable for binsplitting (i.e. with the format `<SAMPLE><SEPARATOR><CONTIGNAME>`?) Since that is what ultimately determines the bin names.

**Comment by chassenr** [comment]
The rules that I am using for the VAMB part are:

```
rule prepare_vamb:
	input:
		contigs = expand(config["adir"] + "/Intermediate_results/" + config["analysis"] + "/Single_assembly/{sample}_metaspades/contigs.fasta", sample = SAMPLES)
	output:
		concat = config["adir"] + "/Intermediate_results/" + config["analysis"] + "/Single_binning/vamb_binning/catalogue.fna.gz"
	conda: config["wdir"] + "/envs/vamb.yaml"
	shell:
		"""
		concatenate.py -m 1000 {output.concat} {input.contigs}
		"""
rule vamb_index:
	input:
		concat = config["adir"] + "/Intermediate_results/" + config["analysis"] + "/Single_binning/vamb_binning/catalogue.fna.gz"
	output:
		index = config["adir"] + "/Intermediate_results/" + config["analysis"] + "/Single_binning/vamb_binning/catalogue.fna.gz.bwt"
	conda: config["wdir"] + "/envs/coverm.yaml"
	shell:
		"""
		bwa index {input.concat}
		"""
# the samtools view command is filtering out supplementary alignments (necessary since mapping was done against contigs from all samples)
# also PCR/optical duplicates are removed and those not passing vendor QC
rule mapping_vamb:
	input:
		clean_R1 = config["adir"] + "/Intermediate_results/" + config["analysis"] + "/Human_cleaned/final/{sample}_1.fastq",
		clean_R2 = config["adir"] + "/Intermediate_results/" + config["analysis"] + "/Human_cleaned/final/{sample}_2.fastq",
		concat = config["adir"] + "/Intermediate_results/" + config["analysis"] + "/Single_binning/vamb_binning/catalogue.fna.gz",
		index = config["adir"] + "/Intermediate_results/" + config["analysis"] + "/Single_binning/vamb_binning/catalogue.fna.gz.bwt"
	output:
		bam = config["adir"] + "/Intermediate_results/" + config["analysis"] + "/Single_binning/vamb_binning/{sample}.bam"
	threads: config["sample_threads"]
	conda: config["wdir"] + "/envs/coverm.yaml"
	shell:
		"""
		bwa mem -v 1 -t {threads} {input.concat} {input.clean_R1} {input.clean_R2} | samtools view -F 3584 -b --threads {threads} > {output.bam}
		"""
# minimum identity of 95% and minimum alignment score of 30
# recommended on https://github.com/RasmussenLab/vamb (date accessed: 2022-03-27)
rule vamb_binning:
	input:
		bam = expand(config["adir"] + "/Intermediate_results/" + config["analysis"] + "/Single_binning/vamb_binning/{sample}.bam", sample = SAMPLES),
		concat = config["adir"] + "/Intermediate_results/" + config["analysis"] + "/Single_binning/vamb_binning/catalogue.fna.gz"
	output:
		log = config["adir"] + "/Intermediate_results/" + config["analysis"] + "/Single_binning/vamb_binning/result/log.txt"
	params:
		vambdir = config["adir"] + "/Intermediate_results/" + config["analysis"] + "/Single_binning/vamb_binning"
	threads: config["parallel_threads"]
	conda: config["wdir"] + "/envs/vamb.yaml"
	shell:
		"""
		vamb --outdir {params.vambdir}/result/tmp --fasta {input.concat} --bamfiles {params.vambdir}/*.bam -o C --minfasta 50000 -z 0.95 -s 30
		mv {params.vambdir}/result/tmp/* {params.vambdir}/result/
		"""
def SID_fun(wildcards):
	return VAMB[wildcards.sample]
rule vamb_split_bins:
	input:
		log = config["adir"] + "/Intermediate_results/" + config["analysis"] + "/Single_binning/vamb_binning/result/log.txt"
	output:
		done = config["adir"] + "/Intermediate_results/" + config["analysis"] + "/Single_binning/{sample}/vamb_done"
	params:
		indir = config["adir"] + "/Intermediate_results/" + config["analysis"] + "/Single_binning/vamb_binning/result/bins",
		outdir = config["adir"] + "/Intermediate_results/" + config["analysis"] + "/Single_binning/{sample}/vamb_bins",
		sid = SID_fun
	shell:
		"""
		SID="{params.sid}"
		mkdir -p {params.outdir}
		cd {params.indir}
		ls -1 *.fna | grep "^${{SID}}C" | while read line
		do
		  sed "/^>/s/${{SID}}C//" $line > {params.outdir}/$line
		done
		touch {output.done}
		"""
```

SAMPLES I get from:

```
# specify wildcards for samples and paths of input file names
sample_table = pd.read_table(config["sample_list"], sep="\t", lineterminator="\n", header=None, names = ["SID", "path_R1", "path_R2"])
SAMPLES = sample_table.SID.to_list()
SID = sample_table.SID.to_list()
PATH_R1 = sample_table.set_index('SID')['path_R1'].to_dict()
PATH_R2 = sample_table.set_index('SID')['path_R2'].to_dict()
# define VAMB sample abbreviations
VAMB = dict(zip(SAMPLES, ["S" + str(i) for i in list(range(1, len(SAMPLES)+1))]))
```

Where config["sample_list"] is pointing to a table with the sample names in the first column.

Maybe this is a very roundabout way of doing this, but so far it seems to work much better than expected.
